#+title: 狂犬病科普
#+AUTHOR: panshishuo
#+date: <2021-12-11 13:12>

#+BEGIN_QUOTE
《狂犬病》，跟大家分享几个很多人都非常关心的问题。
#+END_QUOTE

***** 1. 狂犬病潜伏期多久？
一般认为是 1-3 个月，大多数在被咬后 3 个月内发病。但也有个例报道潜伏期长达 10 年以上。潜伏期长短与年龄、伤口部位、伤口深浅、入侵病毒数量和毒力等因素相关。

***** 2. 狂犬病发病过程如何？几天会死亡？
狂犬病一旦发病，多数会有典型的 3 期临床表现。

- 首先是 前驱期 ，会有低热、乏力、头痛、恶心、全身不舒服，然后恐惧不安、烦躁失眠，对声音、风、光等刺激很敏感。这个阶段持续 2-4 天。
- 接着是 兴奋期 ，高度兴奋、恐惧不安、恐水、恐风、高烧，恐水不一定每个病人都有。患者神志多清晰，少数会有幻觉，本期持续 1-3 天。
- 最后是 麻痹期 ，肌肉痉挛停止，全身瘫痪，昏迷，最终呼吸循环衰竭而死亡，这个阶段一般是 6-18 小时，不超过 1 天。

上述病程一般不超过 6 天。

***** 3. 狂犬病一旦发作，真的死亡率 100% 么？
我们国家的医学教材《传染病学》（第八版）明确表示：狂犬病是所有传染病中最凶险的病毒性疾病，一旦发病，病死率达 100%。

***** 4. 被狗咬了，什么情况下需要注射疫苗？
这是大家最关心的一个问题，也是最关键的一个问题。这涉及到一个专业的概念：暴露。狂犬病暴露是指被狂犬、疑似狂犬、或者不能确定是否患有狂犬病的宿主动物咬伤、抓伤、舔伤粘膜或者破损皮肤处，或者开放性伤口、粘膜直接接触可能含有狂犬病病毒的唾液或者组织。

上述叫做狂犬病暴露。不是所有被狗咬了的都算暴露，一定要是被狂犬、疑似狂犬、或者不能确定是不是狂犬咬伤才算暴露，如果是自己家里的小狗咬到的，小狗一直都是家里养，从来没有外出过，没有接触过其他狗，那是不可能患有狂犬病的，这时候被它咬伤，顶多是咬伤，不会有狂犬病，这种情况不需要接种狂犬病疫苗，前提是你得确保你的狗是清白的。

按照暴露性质和严重程度将狂犬病暴露分为三级：
- Ⅰ 级：接触或喂养动物；或完整的皮肤被舔；或完好的皮肤接触狂犬病动物或人狂犬病病例的分泌物或排泄物。
- Ⅱ 级：裸露的皮肤被轻咬；或无出血的轻微抓伤或擦伤。
- Ⅲ 级：单处或多处贯穿皮肤咬伤或者抓伤（肉眼可见出血或皮下组织）；破损皮肤被舔舐；粘膜被动物唾液污染；或暴露于蝙蝠。发生在头、面、颈部和外生殖器的咬伤属于 Ⅲ 级暴露。

II 级和 III 级暴露者，疫苗接种程序一般是 5 针法，即：第 0（当天）、3、7、14、28 天个接种 1 针，总共 5 针。

***** 5. 很多人说的 10 日观察法是什么？什么情况适合用？
每次有医生科普疫苗的重要性，评论区都会有一堆人说 WHO 的 10 日观察法，他们意思是说，被狗咬了不要紧，只要观察这只狗 10 日内会不会死掉就行了，如果肇事狗 10 日内死掉了（可能是狂犬病发病死掉），那就赶紧滴，接种疫苗。如果肇事狗过了 10 天还活蹦乱跳，那几没事了，不用接种疫苗。
上述做法是不恰当的。

WHO 及美国 CDC 推荐的 10 日观察法的确存在，国际上承认，但是有很多限制的：
1. 10 日观察法仅仅限于家养的狗、猫等，而且伤人动物需有2次明确记载有效的狂犬病疫苗接种史，否则不要拿命开玩笑；
2. 肇事动物能不能被我隔离观察？如果是自家的狗那是可以观察 10 天的，如果是流浪狗，它咬了我一口，还会停留在那里给我观察 10 天不成？
3. 这是最重要的，暴露后应该立即接种疫苗，不要等 10 天后再来决定是否接种，否则可能错失良机。但是如果 10 天后我们能看到肇事动物仍然存活，那么接下来的2针（第 14 天、第 28 天）就不用打了。

综上所述，大家一定要谨慎对待 10 日观察法。10 日观察法是科学的，但一定是有前提条件的，不是说被狗咬了咱们等 10 天，看它死不死，它如果不死，咱就不接种疫苗，它死了咱就赶紧接种，不是这样的。

***** 6. 有人质疑狂犬病疫苗滥用
这是个大问题，也是涉及面很广的问题，很多医生都研究不透，没办法给出建议，建议大家具体问题具体分析，当自己被狗咬了，综合分析，到底要不要打疫苗。
