#+title: 一些必须知道的常识
#+AUTHOR: panshishuo
#+date: <2021-12-14 05:24>

#+BEGIN_QUOTE
@@html:<b>人生而无知，但是并不愚蠢，是教育（洗脑）使人愚蠢。</b>@@
#+END_QUOTE

***** 教育的本质是什么？

当年米开朗基罗做成大卫之后，自己也觉得震撼，所有人都震撼，连记者也问米开朗基罗：“您是怎么创作出如此伟大的作品”？他没有轻易地回答。他说让我想一想，他想了半天以后，很慎重地回答：“不是我创造出这么伟大的作品，是那个石头里本来就有一个大卫，我只是把他释放了出来。”这句话太精彩了。

这句话才是千古教育的本质，每个人身体里都有一个更好的自我，甚至是伟大的自我，每个孩子的身体里，都一定有一个自我，教育的本质，作为家长也好，老师也好，其实就是帮助他释放出那个伟大的自我。

***** 社会的一套评价系统
有些话讲出来，既得罪穷人又得罪富人。社会有一套评价系统，先天牌不好会处处被碾压，富人财富自由不工作被看作理所当然，穷人收入捉襟见肘没动力工作被污名为懒惰。

宏大叙事是以牺牲或降低普通人(中产以下底层)的社会福利实现的，技术进步可能掩盖和助长了傲慢或愚昧的价值观。最好的永远只给“成功”的群体，多数普通人凭每月 108 元养老金自生自灭。《走出韩国》这本书的作者写过大韩民国只爱金妍儿，不爱我这样的普通人。

***** 怎么独立阅读而不被潮流裹挟

- 认同独立思考；
- 建立思考习惯：习惯比工具有效；
- 学会研究：好奇，自问为什么、自己找答案；
- 基于事实：客观对待观点，远离态度；
- 对比阅读：了解不同观点；
- 了解弱势信息：看看第二名；
- 避免站队：敌人的敌人通常不是朋友；
- 晚点再读：避免冲动阅读。

***** 洞穴之喻

柏拉图“洞穴之喻”：设想在一个地穴中有一批囚徒，他们自小呆在那里，被锁链束缚，只能看面前洞壁上的影子，头无法动，看不见洞壁反方向的东西。在他们后上方有一堆火，有一条横贯洞穴的小道：沿小道筑有一堵矮墙，如同木偶戏的屏风。人们打着各种器具走过墙后的小道，而火光则把透出墙的器具投影到囚徒面前的洞壁上。囚徒自然地认为影子是唯一真实的事物。如果他们中的一个碰巧获释，转过头来看到了火光与物体，他最初会感到困惑，他的眼睛会感到痛苦，他甚至会认为影子比它们的原物更真实。

如果有人进一步拉他走出洞穴，到阳光下的世界，他会更加眩目，甚至会发火：起初他只能看事物在水中的倒影，然后才能看阳光中的事物，最后甚至能看太阳自身。到那时他才处于真正的解放状态，会开始怜悯他的囚徒同伴、他原来的信仰和生活。如果他返回去拯救他的囚徒同伴，他得有一段时间去适应洞中的黑暗，并且会发现很难说服他们跟他走出洞穴。

***** 赚钱这件事
赚钱这件事，没有人能够教给我们。

能教的只是技能、手艺，商业思维这种东西教不出来，教了你不到那个程度你悟不到。

有很多人付费学商业思维，这个能讲但学不学出来，完全看你运气，对于有的人那是点拨、那是窗户纸一捅就明，对于有的人那是耳旁风，同样的知识，不同的领悟。

***** 屯粮的方法

屯粮的方法（用于保存一年以上食物）：
1、主食：密封的大米、面粉、干豆、方便面；
2、食用油；
3、调味品：盐、糖、高度酒、干货；
4、肉菜：冷冻肉、冷冻蔬菜（美式杂菜）；
5、罐头；
6、饮品：咖啡豆、茶叶、奶粉。

保存方法是：1、常温类：抽干空气密封并放在背光处。2、冷冻类：放入冰箱冷冻室。

***** 你永远赚不到超过你认知范围的钱赚钱这件事，没有人能够教给你 能教的只是技能、手艺，商业思维这种东西，教不出来，教了你不到那个程度你悟不到。 有很多人付费学商业思维这个能讲但学不学出来，完全看你运气对于有的人，那是点拨，那是窗户纸一捅就明对于有的人那是耳旁风累牍 同样的知识，不同的领悟
你永远赚不到

超出你认知范围外的钱除非你靠运气

但是靠运气赚到的钱

最后往往又会靠实力亏掉这是一种必然

你所赚的每一分钱

都是你对这个世界认知的变现你所亏的每一分钱

都是因为对这个世界认知有缺陷这个世界最大的公平在于：

当一个人的财富大于自己认知的时候这个社会有100种方法收割你

直到你的认知和财富相匹配为止

***** 反诈灵魂 8 问
防范诈骗需牢记：不听·不信·不转账。

1. 刷单前问问自己，动动手指就能赚钱的好事为啥能轮到你？

2. 网恋前问问自己，人靓声甜的小姐姐，温柔帅气又有钱的小哥哥，为啥还需要网恋？

3. 收到逮捕令时问问自己，抓人还要提前通知警察是不是觉得自己太闲，怕坏人跑路跑得不够快？

4. 裸聊前问问自己，自己的身材值不值得美女与你“坦诚相见”？

5. 网贷前问问自己，无抵押还免息，对方为啥不直接送钱给你？

6. 点陌生链接前问问自己，查信息就查信息，为啥还要下载一堆东西？

7. 理财前问问自己，战无不胜的投资大师为啥要苦口婆心帮助非亲非故的你？

8. 给领导转账前问问自己，用自己微信公然收受巨额资金，领导是不是嫌自己官儿干久了？

***** 志同道合才能生活容易

1. 不要和自己的天性对抗，喜欢自由，就不要进体制内去工作。喜欢简单，就不要去复杂的环境里生活。事实上，简单有时候比复杂更难做到。

2. 定期自省，跳出自己的身体，跳出自己的环境，在半空中审视那个坐在电脑前敲字的自己，是不是又做了蠢事。

3. 和有智慧的人交流，英雄不问出处，智者不论年龄，听他们说话，但不照搬他们的话。

4. 努力去做自己擅长和喜欢的事情。很多人喜欢的不擅长擅长的不喜欢，更多人没机会做真正想做的事。

5. 和自己喜欢并且喜欢自己的人在一起工作和生活。和而不同，和更重要。

贾樟柯在十三邀的访谈里说：我越来越对形成共识不感兴趣。因为共识的形成是非常疲惫的过程，非常消耗创造力，共识应该是自己来达成自己的认识，在自己的认识里突飞猛进，如果停滞在共识的讨论中，那是某种教育应该承担的责任，不是艺术家的责任。

找到能有共识的人，找到理解，生活会更容易一点。

***** 穷人为什么难翻身
1. 成熟晚

    他们中大多要到 30 多岁，才能明白社会的运行逻辑和人性。俗话说，穷人家的孩子早当家，其实哪里是早当家，只是在极端环境下掌握了一些基本生存技巧而已，英文叫“street smart”。

2. 没有建设性的指导

    一个几代人穷且老实的家庭，30 岁前最大阻力来自于家人。他们没有足够的认知层次和人脉去给出指引和帮助，甚至还会帮倒忙。很多穷人家叛逆的孩子反而容易成功，就是因为他们早早摆脱了原生家庭的束缚。某瓣就有控诉原生家庭的很多小组，叫“父母即祸害”，虽然偏激，但不无道理。

3. 没有试错资本

    有钱家孩子可以试错，不断试，不断成长，一般家庭的孩子大部分错一次，就跌入谷底，从此起起伏伏，背负着家庭的压力，跌入轮回的循环，很难翻身。

我们需要记住的是：勤劳一定能解决温饱，但不一定能致富。

穷人难翻身，其实说穿了就是“信息层级差异”，说传统些就是“掌握的情报不同”。

没有足够的情报网，任你多智近妖、再世诸葛的军师，也打不了胜仗。其实大多数时候，智慧都是建立在信息的基础上，没有足够的信息供你吸收分析成长，智慧就无法产生。不同阶级家庭所能接触，接收到的信息差异实在是太大了。

穷人家的孩子更缺乏具备获取信息的能力，凭借自己能力得到的信息更不具备价值。穷人身边的人，送他信息往往也没用。

***** 不必为了不孤独而合群
"孤独是一种情绪，其主要特点是，因为觉得和外界缺乏有亲密感的连接，而产生的痛感"。

很多人为了避免这种痛苦，凑合着和自己并不真正同频的人厮混，之后感觉更无聊和孤独。

换个角度看，如果你完全没有"孤独感"，就有风险被一群狐朋狗友带偏，在重大抉择上严重缺乏判断力。

***** 人与人最大的差别是思维
如果你觉得世界不公平，可能本质上还是你不够强大，你还没有做得足够好。其实，人与人之间的差异并没有我们想象中的大，与其说是智商的差异，不如说是思维的差异。我们生活在一个处处不公平的世界，我们无法改变这个世界的规则，无法改变自己的过去，但至少可以改变我们面对这个世界的心态，改变自己对于过去的看法，用一种新的思维模式，重新面对这个世界。

如果你愿意，你总是可以掌控点什么。谁没有痛苦，谁没有纠结呢？除非你的受害者模式让你深深陷入抱怨与自怜之中。只要你愿意用一种掌控者的心态去重新面对自己的工作和生活，你就会感受到幸福。

***** 一位离婚律师揭露的婚姻真相
1. 结婚不要太早；
2. 不要做全职妈妈；
3. 不要相信爱会持续一生；
4. 婚姻里，钱真的很重要；
5. 你的伴侣大概率是会出轨的，或精神或肉体；
6. 孩子不是拯救婚姻的法宝；
7. 婚姻是一条路，你们要同行，要共同成长；

***** 钱理群教授对鲁迅的评价
鲁迅，他把自己的困惑、自己的不理解、自己的矛盾都同时告诉你。他的目的是什么呢，逼得你和他一起思考，他的目的不是给你指路，他说很清楚“我也不知道路怎么走，我怎么给别人指路”，所以鲁迅拒绝了当导师。

所以鲁迅的意义，如果你有困难、有困惑，你到鲁迅那里找道路，就找错人了！他不是给你解决问题的人、不是给你指路的人。

鲁迅是最好的朋友，因为在鲁迅面前你是独立的，你完全可以批评他、质疑他，他和你一起讨论。经常开玩笑说老师最大的毛病就想收编学生，但是真正的知识分子，他是要学生独立成人的。

我觉得今天为什么需要鲁迅，他有三个拒绝：第一个，他拒绝被体制收编；第二个，拒绝被任何思想体系收编；第三个，他拒绝、也不收编我们。

鲁迅他最大的意义就是帮助我们，是帮助、不是指导，帮助我们每一个人成为一个独立自主的、独立思考的一个真正的人。

***** [[../history/rr_gaomi_jiefa.org][谈告密与揭发]]
1. 不告密、不揭发，与其说是一种可贵品质，不如说是一条道德底线。告密成风的社会，是人人自危的社会，告密使人与人之间失去基本信任，甚至相互侵害，冲击人们的价值判断，毁掉社会的道德基础。

2. “我不知道，查理今天的缄默是对还是错，但我可以告诉你，他决不会出卖别人以求前程。而这，朋友们，就叫正直，也叫勇气，那才是领袖的要件！”这段话，是美国电影《闻香识女人》中的一段台词。

***** 道德是自律，而不是他律
“道德是自律，而不是他律”，这就是为什么我对自己，保持谨慎的悲观主义，因为道德主要是自省，当我们用道德来自省的时候，会发现自己真的是个坏人，真的会时常觉得自己是个坏人。

我们内心中有很多很坏的想法、很多很邪恶的想法，我们的内心就像阴沟一样散发出阵阵的恶臭，当然别人是闻不见的，别人闻到都是香饽饽的、都是道貌盎然的。但是我们自己在夜深人静的时候，能闻得到自己内心那种阴沟的幽暗，所以我们需要被约束。

当然，对于他人，我们没法看到他的内心、没有这种能力去监察别人的内心，所以，这就是为什么我们要与人为善，为什么不要轻易对别人做道德上的评价。

道德评价，要评价自己而不是评价别人。我们不能整天去说自己闻得见别人身上的阴沟味道，我们应该闻闻自己身上的阴沟味，我们会发现自己身上全是阴沟味。

我们不能动不动就说别人，“这个人太臭了”。我们说别人臭，其实很可能是自己臭。据说一个口臭的人绝对不会想到自己有口臭，他只是闻到别人有口臭；自己脸上有麻疹，自己看不见，但是别人脸上的麻疹，自己全都看得见。这是不道德的，不道德不代表违法，就算违法不代表这是犯罪。

我们永远要对自己内心的幽暗保持足够的警惕。而且我们需要知道的是，我们越往道德高峰去跑，我们会越觉得自己无比的幽暗。

—— 罗翔

***** 短期和长期，被动和主动
历史上让聪明人就范的一个屡试不爽的方法，是许诺或提供相当可观的短期利益，但同时客观上限制或极大削弱其对未来的选择权。

底子越薄的人，越无法拒绝这种诱惑。等到他跳到这个坑里面，最后完全丧失选择权后，就可以再从他那里收回远高于以前若干倍的投入。

缺乏历史视野，缺乏全面信息网络，缺钱的人，基本无法抵御这种陷阱。因为他完全无法理解，他的未来还有哪些其它更好的选择，也就无法理解他现在的行为是在放弃这些选择权。

他如果拒绝这些短期利益的话，很可能被所在团体其他缺钱的人视为傻逼，所以默认的结局是被周围的人裹挟着，一起落入陷阱。

***** 如何选择配偶
其实，给你倒温水，半夜给你买烧烤，这些都不是稀有的物种。

而现实是，有些人，无论男女，却偏偏为这种低成本的付出，感动的死去活来。

真正的稀缺资源是对方的谈吐，对方的知识面，对方的商业视野，对方控制局面的能力，对方的情绪稳定。不要小看上面这些特点，要培养这些优点，所耗成本是极高的，可遇而不可求。

最佳的配偶，是你人生战场的盟友，而不是找一个人人满足你的懒惰和巨婴。

—— 稻盛和夫

***** TikTok 算法如何让用户上瘾。
简单公式是： =P点赞 * V点赞 + P评论 * V评论 + E播放时长 * V播放时长 + P播放 * V播放= 。

即跟“点赞、评论和播放时长”有关。

***** 利率 —— 常见的资金成本
发现不少人对资金成本没概念，简单讲下。

年息 8% 以下，属于低成本资金，这种属于稀缺资源，如果能长期拿到这种成本的钱，你就是个香饽饽。

年息 8% 至 15%，正常资金成本，朋友之间，亲戚之间，相熟的老板之间，以这个利率拆借常见，有情义成分在里面。

年息 15% 至 24%，中高利率成本，不太熟的关系之间互相借钱，某些金融机构的信用贷分期等利率，信用卡逾期利率也是万分之五利息，不算复利的话，都在这个区间。

24% 以上，高利率成本，我们国家有规定，利率高于 24%，起诉的话法院会不予支持。但民间依然会有人借这种钱，一分钱难倒英雄汉，不得不借是因为没别的途径了。

上面说的都是中长期的借款，如果短期向金融机构借钱利率都较高，比如买房担保过桥，按日计息万分之八或者千分之一，年化 36%。

***** 普通人如何做基本的财务规划
（@@html:<b>以上仅仅作为一个粗略的框架和方向性建议，不代表专业意见</b>@@）

1. 还清所有网贷、小额贷、消费贷，从负债消费状态到现金结余状态；

2. 储蓄至少 6 到 12 个月的生活费或者等额月工资，以保证自己在工作变动状况下有机动资金，该资金可以以现金理财保留，不做任何消费；

3. 在此基础上每个月强制储蓄五分之一或者四分之一的月收入，这部分可以购买货币基金或者定投指数基金；

4. 这个阶段目标是积累购房首付款，创造自己拥有在合适时机刚需时刻可以出手购房的能力；

5. 主业副业多轮驱动增加财富来源，让自己的生活开支尽量占收入的三成以下，保证有更多的资金用于理财或者其他稳健投资；

6. 伴随经济能力适时配置房产，小中户型入手；

7. 放大自己能力创造更多财富，第一阶段有一百万的理财资金；

8. 进阶财富自由阶段，扣除负债及唯一房产以后的净资产年化收益等于自己一年的消费，比如一年消费 10 万，那么至少需要完成 250 万的净资产积累。

核心注意事项：不借钱消费！不借钱给别人！不超前消费！目标没有达到的时候抹下面子赚钱，这是最重要的人生目标之一！

***** 关于副业的 5 个大类
1. 卖时间。如果你没有明确的技能，又想多赚钱，那就是去卖自己的本来可以休息的时间去兼职。比如做快餐厅的兼职，比如做一个网上客服的兼职，不要看不起这些收入，在自己一穷二白的情况下，都比躺家里刷手机强，很多优秀的人，都是这个过程中起来的。

2. 卖技能。如果自己有点技能，那就用业余时间接活，比如做财务的，就给小公司做兼职会计，每个月做账帮报税，当老师的就去做家教，会平面设计的就去接点私活，这种副业的特点就要卖服务。卖服务比单纯卖时间强，特点是有技能的附加值。如果没有这些技能，可以先学一个，然后通过技能去做副业，比如现在比较火的短视频制作。但是技能换钱的本质还是用时间换钱，只是价值更高。

3. 商品换钱。线上线下都可以，有很多人搞点货源，在天桥上、车屁股后面，小区门口支个摊就可以赚钱。我很小的时候，把家里的小人书放广场上，别人看一本给几分钱，也赚了不少钱。不愿意线下卖的，现在通过朋友圈，小红S，各种渠道去引流带货销售都是用商品换钱。这里面其实很简单，花点心思找到好货源，自己要有点眼光，然后持续的营销就可以，毕竟社交电商还是有很长的未来。

4. 复合技能赚钱。比如你会做 PPT 或者做视频，那自己做一个教程，线上线下教大家开课，这种副业需要你除了有内容，还需要表达输出能力，能让别人听懂，这样你可以不用亲自做 PPT，而是输出知识和有效信息，所以这一类就可以划在知识付费赚钱里面。

5. 流量赚钱。如果你经营自己有名气了，随便接个广告，代言赚流量的钱。总之你能力越强，赚钱的可能性就越多。

所以只要有时间，想多赚钱，副业的机会是很多，但是做什么都有付出，千万别相信什么投入多少钱月赚百分之多少的项目，这个不是副业，是骗局。


***** 知识付费不能解决赚到钱的痛点
知识付费（包括我们自己学习知识本身），几乎全部都只能解决“痒点问题”，解决不了“痛点问题”。

“痒点问题”，就是大家想赚钱产生的焦虑 —— 想提高自己。于是知识付费博主开设课程，解决我们的痒点问题，结果是我们确实能缓解焦虑，能学到一些东西，同时他也能赚钱。

但是，“痛点问题” —— 我们想赚钱，他们都解决不了这个问题 —— 我们学完了根本赚不到钱。

而更大的问题是 —— 没有人敢说出真相 —— 那就是大部分人根本没有学习能力。因为大部分人连做事情的方法、基本功和理解力都没有，根本不可能赚到钱 —— 他们只配穷。

虽然这个市场依然会存在，一些人依然会为了“解决痒点”去报课，博主依然可以通过“解决痒点”的方式去赚钱。但本质上 —— 一条鱼被钓上来一次，算它运气差，被钓上来两次就是傻鱼了，被钓上来三次，你最好不要吃了，这是个智障鱼，吃了它影响你自己的智商。

这种“解决痒点”的商业模式应该非常不被看好，本质上没有发展势能。

即使是再牛逼的平台和账号，这种模式跑上两三年就基本没有势能了，因为本质上还是——只能“解决痒点”，不能“解决痛点”。

要“解决痛点”，必须全面重新革新商业模式。重新定义行业价值。重新定义教育价值。


***** 贪好有度
对钱贪婪一点可以，别陷进去，比一般人活得好，就是八十分了，然后心态淡然一点；同理，对色痴迷一点可以，别陷进去，现实的能力兜不住变态的行为，那就迷失了，也会和陷入钱里一样被制裁。

有钱够花不拮据，去哪旅游咱们也能去，住不了五星级酒店，住快捷也行；不说顿顿山珍海味，偶尔来一次也没问题。自己也有能力满足自己对色的需求。这就是一个比较完美的状态了。

***** 教育与洗脑的区别
洗脑：我挖了一条捷径，跟着我走就行。
教育：世界上没有捷径，做自己就好。

洗脑：听懂，掌声……
教育：大家安静思考，寻找属于自己的答案。

洗脑：不要想那么多，跟着我就有肉吃。
教育：你需要找到你自己，这是你变强大的前提。

洗脑：通过各种干扰，阻止你独立思考。
教育：制造各种问题，启发你独立思考。

洗脑：让你盲从，逐渐成为不会思考的工具。
教育：让你成长，逐渐成为自己人生路上的武器。

洗脑：自古真心留不住，唯有套路得人心。（这便是洗脑容易得手的原因。）
教育：书山有路勤为径，学海无涯苦作舟。（所以人间正道无人问津啊。）

总结一下：@@html:<b>洗脑会让人舒服地沉沦</b>@@。
