#+title: 一些必须知道的常识
#+AUTHOR: panshishuo
#+date: <2021-12-14 05:24>

#+BEGIN_QUOTE
人生而无知，但是并不愚蠢，是教育（洗脑）使人愚蠢。
#+END_QUOTE

***** 穷人为什么难翻身
1. 成熟晚：他们中大多要到 30 多岁，才能明白社会的运行逻辑和人性。俗话说，穷人家的孩子早当家，其实哪里是早当家，只是在极端环境下掌握了一些基本生存技巧而已，英文叫“street smart”。
2. 没有建设性的指导：一个几代人穷且老实的家庭，30 岁前最大阻力来自于家人。他们没有足够的认知层次和人脉去给出指引和帮助，甚至还会帮倒忙。很多穷人家叛逆的孩子反而容易成功，就是因为他们早早摆脱了原生家庭的束缚。某瓣就有控诉原生家庭的很多小组，叫“父母即祸害”，虽然偏激，但不无道理。
3. 没有试错资本：有钱家孩子可以试错，不断试，不断成长，一般家庭的孩子大部分错一次，就跌入谷底，从此起起伏伏，背负着家庭的压力，跌入轮回的循环，很难翻身。

***** 不必为了不孤独而合群
"孤独是一种情绪，其主要特点是，因为觉得和外界缺乏有亲密感的连接，而产生的痛感"。

很多人为了避免这种痛苦，凑合着和自己并不真正同频的人厮混，之后感觉更无聊和孤独。

换个角度看，如果你完全没有"孤独感"，就有风险被一群狐朋狗友带偏，在重大抉择上严重缺乏判断力。

***** 人与人最大的差别是思维
如果你觉得世界不公平，可能本质上还是你不够强大，你还没有做得足够好。其实，人与人之间的差异并没有我们想象中的大，与其说是智商的差异，不如说是思维的差异。我们生活在一个处处不公平的世界，我们无法改变这个世界的规则，无法改变自己的过去，但至少可以改变我们面对这个世界的心态，改变自己对于过去的看法，用一种新的思维模式，重新面对这个世界。

如果你愿意，你总是可以掌控点什么。谁没有痛苦，谁没有纠结呢？除非你的受害者模式让你深深陷入抱怨与自怜之中。只要你愿意用一种掌控者的心态去重新面对自己的工作和生活，你就会感受到幸福。

***** 一位离婚律师揭露的婚姻真相
1. 结婚不要太早；
2. 不要做全职妈妈；
3. 不要相信爱会持续一生；
4. 婚姻里，钱真的很重要；
5. 你的伴侣大概率是会出轨的，或精神或肉体；
6. 孩子不是拯救婚姻的法宝；
7. 婚姻是一条路，你们要同行，要共同成长；

***** 钱理群教授对鲁迅的评价
鲁迅，他把自己的困惑、自己的不理解、自己的矛盾都同时告诉你。他的目的是什么呢，逼得你和他一起思考，他的目的不是给你指路，他说很清楚“我也不知道路怎么走，我怎么给别人指路”，所以鲁迅拒绝了当导师。

所以鲁迅的意义，如果你有困难、有困惑，你到鲁迅那里找道路，就找错人了！他不是给你解决问题的人、不是给你指路的人。

鲁迅是最好的朋友，因为在鲁迅面前你是独立的，你完全可以批评他、质疑他，他和你一起讨论。经常开玩笑说老师最大的毛病就想收编学生，但是真正的知识分子，他是要学生独立成人的。

我觉得今天为什么需要鲁迅，他有三个拒绝：第一个，他拒绝被体制收编；第二个，拒绝被任何思想体系收编；第三个，他拒绝、也不收编我们。

鲁迅他最大的意义就是帮助我们，是帮助、不是指导，帮助我们每一个人成为一个独立自主的、独立思考的一个真正的人。

***** [[../history/rr_gaomi_jiefa.org][谈告密与揭发]]
1. 不告密、不揭发，与其说是一种可贵品质，不如说是一条道德底线。告密成风的社会，是人人自危的社会，告密使人与人之间失去基本信任，甚至相互侵害，冲击人们的价值判断，毁掉社会的道德基础。

2. “我不知道，查理今天的缄默是对还是错，但我可以告诉你，他决不会出卖别人以求前程。而这，朋友们，就叫正直，也叫勇气，那才是领袖的要件！”这段话，是美国电影《闻香识女人》中的一段台词。

***** 道德是自律，而不是他律
“道德是自律，而不是他律”，这就是为什么我对自己，保持谨慎的悲观主义，因为道德主要是自省，当我们用道德来自省的时候，会发现自己真的是个坏人，真的会时常觉得自己是个坏人。

我们内心中有很多很坏的想法、很多很邪恶的想法，我们的内心就像阴沟一样散发出阵阵的恶臭，当然别人是闻不见的，别人闻到都是香饽饽的、都是道貌盎然的。但是我们自己在夜深人静的时候，能闻得到自己内心那种阴沟的幽暗，所以我们需要被约束。

当然，对于他人，我们没法看到他的内心、没有这种能力去监察别人的内心，所以，这就是为什么我们要与人为善，为什么不要轻易对别人做道德上的评价。

道德评价，要评价自己而不是评价别人。我们不能整天去说自己闻得见别人身上的阴沟味道，我们应该闻闻自己身上的阴沟味，我们会发现自己身上全是阴沟味。

我们不能动不动就说别人，“这个人太臭了”。我们说别人臭，其实很可能是自己臭。据说一个口臭的人绝对不会想到自己有口臭，他只是闻到别人有口臭；自己脸上有麻疹，自己看不见，但是别人脸上的麻疹，自己全都看得见。这是不道德的，不道德不代表违法，就算违法不代表这是犯罪。

我们永远要对自己内心的幽暗保持足够的警惕。而且我们需要知道的是，我们越往道德高峰去跑，我们会越觉得自己无比的幽暗。

—— 罗翔

***** 短期和长期，被动和主动
历史上让聪明人就范的一个屡试不爽的方法，是许诺或提供相当可观的短期利益，但同时客观上限制或极大削弱其对未来的选择权。

底子越薄的人，越无法拒绝这种诱惑。等到他跳到这个坑里面，最后完全丧失选择权后，就可以再从他那里收回远高于以前若干倍的投入。

缺乏历史视野，缺乏全面信息网络，缺钱的人，基本无法抵御这种陷阱。因为他完全无法理解，他的未来还有哪些其它更好的选择，也就无法理解他现在的行为是在放弃这些选择权。

他如果拒绝这些短期利益的话，很可能被所在团体其他缺钱的人视为傻逼，所以默认的结局是被周围的人裹挟着，一起落入陷阱。

***** 如何选择配偶
其实，给你倒温水，半夜给你买烧烤，这些都不是稀有的物种。

而现实是，有些人，无论男女，却偏偏为这种低成本的付出，感动的死去活来。

真正的稀缺资源是对方的谈吐，对方的知识面，对方的商业视野，对方控制局面的能力，对方的情绪稳定。不要小看上面这些特点，要培养这些优点，所耗成本是极高的，可遇而不可求。

最佳的配偶，是你人生战场的盟友，而不是找一个人人满足你的懒惰和巨婴。

—— 稻盛和夫

***** TikTok 算法如何让用户上瘾。
简单公式是： =P点赞 * V点赞 + P评论 * V评论 + E播放时长 * V播放时长 + P播放 * V播放= 。

即跟“点赞、评论和播放时长”有关。

***** 利率 —— 常见的资金成本
发现不少人对资金成本没概念，简单讲下。

年息 8% 以下，属于低成本资金，这种属于稀缺资源，如果能长期拿到这种成本的钱，你就是个香饽饽。

年息 8% 至 15%，正常资金成本，朋友之间，亲戚之间，相熟的老板之间，以这个利率拆借常见，有情义成分在里面。

年息 15% 至 24%，中高利率成本，不太熟的关系之间互相借钱，某些金融机构的信用贷分期等利率，信用卡逾期利率也是万分之五利息，不算复利的话，都在这个区间。

24% 以上，高利率成本，我们国家有规定，利率高于 24%，起诉的话法院会不予支持。但民间依然会有人借这种钱，一分钱难倒英雄汉，不得不借是因为没别的途径了。

上面说的都是中长期的借款，如果短期向金融机构借钱利率都较高，比如买房担保过桥，按日计息万分之八或者千分之一，年化 36%。

***** 普通人如何做基本的财务规划
（@@html:<b>以上仅仅作为一个粗略的框架和方向性建议，不代表专业意见</b>@@）

1. 还清所有网贷、小额贷、消费贷，从负债消费状态到现金结余状态；

2. 储蓄至少 6 到 12 个月的生活费或者等额月工资，以保证自己在工作变动状况下有机动资金，该资金可以以现金理财保留，不做任何消费；

3. 在此基础上每个月强制储蓄五分之一或者四分之一的月收入，这部分可以购买货币基金或者定投指数基金；

4. 这个阶段目标是积累购房首付款，创造自己拥有在合适时机刚需时刻可以出手购房的能力；

5. 主业副业多轮驱动增加财富来源，让自己的生活开支尽量占收入的三成以下，保证有更多的资金用于理财或者其他稳健投资；

6. 伴随经济能力适时配置房产，小中户型入手；

7. 放大自己能力创造更多财富，第一阶段有一百万的理财资金；

8. 进阶财富自由阶段，扣除负债及唯一房产以后的净资产年化收益等于自己一年的消费，比如一年消费 10 万，那么至少需要完成 250 万的净资产积累。

核心注意事项：不借钱消费！不借钱给别人！不超前消费！目标没有达到的时候抹下面子赚钱，这是最重要的人生目标之一！

***** 关于副业的 5 个大类
1. 卖时间。如果你没有明确的技能，又想多赚钱，那就是去卖自己的本来可以休息的时间去兼职。比如做快餐厅的兼职，比如做一个网上客服的兼职，不要看不起这些收入，在自己一穷二白的情况下，都比躺家里刷手机强，很多优秀的人，都是这个过程中起来的。

2. 卖技能。如果自己有点技能，那就用业余时间接活，比如做财务的，就给小公司做兼职会计，每个月做账帮报税，当老师的就去做家教，会平面设计的就去接点私活，这种副业的特点就要卖服务。卖服务比单纯卖时间强，特点是有技能的附加值。如果没有这些技能，可以先学一个，然后通过技能去做副业，比如现在比较火的短视频制作。但是技能换钱的本质还是用时间换钱，只是价值更高。

3. 商品换钱。线上线下都可以，有很多人搞点货源，在天桥上、车屁股后面，小区门口支个摊就可以赚钱。我很小的时候，把家里的小人书放广场上，别人看一本给几分钱，也赚了不少钱。不愿意线下卖的，现在通过朋友圈，小红S，各种渠道去引流带货销售都是用商品换钱。这里面其实很简单，花点心思找到好货源，自己要有点眼光，然后持续的营销就可以，毕竟社交电商还是有很长的未来。

4. 复合技能赚钱。比如你会做 PPT 或者做视频，那自己做一个教程，线上线下教大家开课，这种副业需要你除了有内容，还需要表达输出能力，能让别人听懂，这样你可以不用亲自做 PPT，而是输出知识和有效信息，所以这一类就可以划在知识付费赚钱里面。

5. 流量赚钱。如果你经营自己有名气了，随便接个广告，代言赚流量的钱。总之你能力越强，赚钱的可能性就越多。

所以只要有时间，想多赚钱，副业的机会是很多，但是做什么都有付出，千万别相信什么投入多少钱月赚百分之多少的项目，这个不是副业，是骗局。

***** 教育与洗脑的区别
洗脑：我挖了一条捷径，跟着我走就行。
教育：世界上没有捷径，做自己就好。

洗脑：听懂，掌声……
教育：大家安静思考，寻找属于自己的答案。

洗脑：不要想那么多，跟着我就有肉吃。
教育：你需要找到你自己，这是你变强大的前提。

洗脑：通过各种干扰，阻止你独立思考。
教育：制造各种问题，启发你独立思考。

洗脑：让你盲从，逐渐成为不会思考的工具。
教育：让你成长，逐渐成为自己人生路上的武器。

洗脑：自古真心留不住，唯有套路得人心。（这便是洗脑容易得手的原因。）
教育：书山有路勤为径，学海无涯苦作舟。（所以人间正道无人问津啊。）

总结一下：@@html:<b>洗脑会让人舒服地沉沦</b>@@。
