#+title: 2021 年 12 月随笔
#+AUTHOR: panshishuo
#+date: <2021-11-30 17:24>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="static/myStyle.css" />
#+HTML_HEAD_EXTRA: <meta charset="utf-8">
#+HTML_HEAD_EXTRA: <script async type="text/javascript" src="https://cdn.rawgit.com/mathjax/MathJax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

**** 随想
- 什么是自由？自由是对公权力的批评不受公权力的制约，而不是自由的吃喝拉撒，那是猪。
- 如果你对每只向你吠的狗，都停下来扔石头，你永远到不了目的地。 —— 丘吉尔


**** 人类愚蠢定律
	第一条基本定律：总是且不可避免地每个人都低估了流通中的愚蠢个体的数量。

	第二条基本定律：某个人变得愚蠢的可能性与该人的任何其他特征无关。

	第三条基本定律：（也是黄金定律）愚蠢的人是指在没有获得任何收益甚至可能蒙受损失的同时给另一人或一群人造成损失的人。

	第四条基本定律：非愚蠢的人总是低估了愚蠢的个人的破坏力。特别是非愚蠢的人经常忘记，在任何时候，任何地方，在任何情况下与愚蠢的人打交道和/或与之交往总是一个代价高昂的错误。

	第五条基本定律：愚蠢的人是最危险的人（该条的推理是：愚蠢的人比土匪更危险）。

**** 朋友少是正常
	朋友少是正常的事情，根据“邓巴数字理论”，人类智力将允许人类拥有稳定社交网络的人数是 148 人，即：人类的社交人数上限为 150 人，精确交往深入跟踪交往的人数为 20 人左右。 人的大脑新皮层大小有限，提供的认知能力只能使一个人维持与大约 150 个人的稳定人际关系，这一数字是人们拥有的、与自己有私人关系的朋友数量。 也就是说，人们可能拥有 150 名好友，甚至更多社交网站的“好友”，但只维持与现实生活中大约 150 个人的“内部圈子”。而“内部圈子”好友在此理论中指一年至少联系一次的人。 再说的简单点，就是首富，他也最多只有 150 个朋友，多了也招呼不过来，而正常人，一般只能和 20 个人保持亲密关系。 这 20 个人里面，算上爸妈，兄弟姐妹，关系好的同事，领导，留给朋友的指标确实也只剩一两个。 所以，有一两个朋友，或者没有朋友，都很正常。

**** 什么是长期主义
	长期主义，只有把时间拉长，我们才能在一个不确定的世界里，得到确定的答案。非长期主义者，只能得到“偶然”的成功，然后在一次次基本概率事件下，归于平庸。

	长期，不是时间的线性，而是时间的“套娃”，所以，所谓的长期主义，是一种能穿越小周期，看透大周期的能力。

	长期的挑战不是枯燥，而是各种不确定。我们没法在出发前作出完美的计划，但是我们必须做好万全的准备、甚至是超量的准备。不死掉，才能一直走下去。

