#+title: 2021 年 12 月随笔
#+AUTHOR: panshishuo
#+date: <2021-11-30 17:24>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="static/myStyle.css" />
#+HTML_HEAD_EXTRA: <meta charset="utf-8">
#+HTML_HEAD_EXTRA: <script async type="text/javascript" src="https://cdn.rawgit.com/mathjax/MathJax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

**** 随想
- 什么是自由？自由是对公权力的批评不受公权力的制约，而不是自由的吃喝拉撒，那是猪。
- 如果你对每只向你吠的狗，都停下来扔石头，你永远到不了目的地。 —— 丘吉尔
- 一个国家走向怎样的未来，很大程度上取决于它如何面对自己的过去。正是从这个意义上来说，一个民族的悲剧其实也可以是它的财富，而拒绝挖掘这个财富则往往导致一个民族在历史的死胡同里原地踏步。
- 中国自秦以来，无所谓国也，皆家而已，一姓之兴则亿兆为之臣妾，其兴也，此一家之兴也，其亡也，此一家之亡也。天子一身，兼宪法，国家，王者三大物，其家亡则一切与之俱亡，顾其所利害者亦利害于一家而已，未尝为天下计也。 —— 严复


**** 人类愚蠢定律
	第一条基本定律：总是且不可避免地每个人都低估了流通中的愚蠢个体的数量。

	第二条基本定律：某个人变得愚蠢的可能性与该人的任何其他特征无关。

	第三条基本定律：（也是黄金定律）愚蠢的人是指在没有获得任何收益甚至可能蒙受损失的同时给另一人或一群人造成损失的人。

	第四条基本定律：非愚蠢的人总是低估了愚蠢的个人的破坏力。特别是非愚蠢的人经常忘记，在任何时候，任何地方，在任何情况下与愚蠢的人打交道和/或与之交往总是一个代价高昂的错误。

	第五条基本定律：愚蠢的人是最危险的人（该条的推理是：愚蠢的人比土匪更危险）。

**** 朋友少是正常
	朋友少是正常的事情，根据“邓巴数字理论”，人类智力将允许人类拥有稳定社交网络的人数是 148 人，即：人类的社交人数上限为 150 人，精确交往深入跟踪交往的人数为 20 人左右。 人的大脑新皮层大小有限，提供的认知能力只能使一个人维持与大约 150 个人的稳定人际关系，这一数字是人们拥有的、与自己有私人关系的朋友数量。 也就是说，人们可能拥有 150 名好友，甚至更多社交网站的“好友”，但只维持与现实生活中大约 150 个人的“内部圈子”。而“内部圈子”好友在此理论中指一年至少联系一次的人。 再说的简单点，就是首富，他也最多只有 150 个朋友，多了也招呼不过来，而正常人，一般只能和 20 个人保持亲密关系。 这 20 个人里面，算上爸妈，兄弟姐妹，关系好的同事，领导，留给朋友的指标确实也只剩一两个。 所以，有一两个朋友，或者没有朋友，都很正常。

**** 什么是长期主义
	长期主义，只有把时间拉长，我们才能在一个不确定的世界里，得到确定的答案。非长期主义者，只能得到“偶然”的成功，然后在一次次基本概率事件下，归于平庸。

	长期，不是时间的线性，而是时间的“套娃”，所以，所谓的长期主义，是一种能穿越小周期，看透大周期的能力。

	长期的挑战不是枯燥，而是各种不确定。我们没法在出发前作出完美的计划，但是我们必须做好万全的准备、甚至是超量的准备。不死掉，才能一直走下去。

**** 世界不是线性
	很多人是线性思维，比如有 a 就会有 b，做了 a 那么 b 就应该发生。

	线性思维的特点是理解不了事情的复杂性和系统性，比如学习是各种知识以及行动的组合，不是一个方法，而是一整套方法。

	又比如婚姻和感情不是顺理成章，而是要像经营一家公司一样面对各种层面的问题，每一项没有处理好都会有问题。

	所有非线性的，都会觉得难以理解，太麻烦。

	问题是，生活本来就是大量复杂系统构成，各种因素各种力量各种因果。

	想用一根线，去理解世界，太单纯。

**** 识字和阅读时两回事
    识字和阅读是两回事。能阅读真正意义上的文章的人是少数。这就是为什么现在最流行的信息流形式是每几十个字就配一张图。即便这种每张图带几十个字的内容，受众比例仍然不大。

    视频相对于文字来说，有效信息密度低得多，信息传递效率也低，并且难以检索。但视频的优点是可以覆盖几乎所有具有视力的人。这一个优点就可以弥补所有缺点。

    而且视频传输信息的过程是连续的。你读书的时候可以一边读一边思考，但看视频的时候很少会这么做。这还不算完，视频的有效信息密度虽然低，但整体信息密度非常高。那些额外的信息就可以用来对受众进行潜移默化，进行暗示，进行操控。

    所有这些，使得视频特别适合用来作为面向中下阶层的工具——无论是什么目的的工具。
