#+title: 10 个“人类高质量陪伴”实用建议
#+AUTHOR: panshishuo
#+date: <2022-01-19 06:00>

***** 陪伴质量的概念

*陪伴质量，简单来说，就是在陪伴的时间里你带给对方的心理感受。 *  美国著名的婚姻辅导专家盖瑞·查普曼曾提出*创造“精心时刻（Qualitytime）”* 。他在对几百名夫妻进行婚姻辅导之后，把人们感受和表达爱的主要方式总结为 *“爱的五种语言”：肯定的话语、精心时刻、礼物、服务的行为和身体接触* 。

“精心时刻”跟我们一般的陪伴最大的差异就是： *你是否会把全部的注意力都放在对方身上* 。比如聚会的时候，每个人都围着饭桌刷手机，这就不能叫“精心时刻”，只能吧“待在一起”，这样的陪伴是低质量的， *因为你不能跟他人建立真正情感上的交流，也不会让对方感到被关注* 。

***** 如何创造精心时刻

1. 保持目光的接触

2. 不要一边听对方说话，一边做别的事

3. 把倾听重点放在“感觉”上
    #+BEGIN_QUOTE
      这不仅给了 ta 倾诉自己感受的机会，也能让对方感到足够的关注。
    #+END_QUOTE

4. 观察肢体语言
    #+BEGIN_QUOTE
      很多时候，我们的语言表示了某种信息，但肢体语言上却诉说着另一种信息。
    #+END_QUOTE

5. 不要打断对方
    #+BEGIN_QUOTE
        当对方讲话的时候，避免为自己辩护、轻易下判断、或者武断地表示自己的立场。记住，你的目标是理解对方，不是证明目对的。
    #+END_QUOTE

6. 练习自我表露
    #+BEGIN_QUOTE
      如果你是一个不善于表达自己情绪的人，可以通过练习表达自己的感受，让对方更理解你。这会帮助你们加深理解，也能增强亲密感。
    #+END_QUOTE

7. 跟对方一起回答这个问题：做什么事情时，我最能感受到你的爱？

8. 计划一次优质活动

9. 去做那些“就是为了 ta 而做”的事
    #+BEGIN_QUOTE
      有一些事可能是对方很在意，但你却不太感兴趣的。这恰恰是你可以努力的方向：告诉自己，我做这件事的目的就是为了让对方感到被爱，这相当于一次“情感储值”。
    #+END_QUOTE

10. 了解和探讨彼此“爱的语言”
    #+BEGIN_QUOTE
      盖瑞·查普曼在他的书中说道，每个人的语言"都是不同的，这和我们幼年时的成长经历有关。而这样的差异会导致“我说了，你没听懂的情况：明明认真付出了，对方却不领你的情，反而给关系造成了负担。
    #+END_QUOTE

***** 写在最后

我想， *“不去期待一劳永逸地解决问题”* 也许就是关于亲密关系最实用的建议之一。你没有办法从一档节目、一部剧或一篇文章里拿到万能钥匙，但终归可以从他人的一些经验中获得一把把小钥匙，提升陪伴质量，可能就是其中的一把钥匙。

*而这些钥匙“实用”的基础，是你们对“未来越来越好”的共同期待、步调一致的努力，以及耐心* 。
