#+title: 以 CEO 的方式去生活
#+AUTHOR: panshishuo
#+date: <2022-01-15 20:00>


**** 相关书籍 [[https://themanagershandbook.com/][The Manager’s Handbook]]

- 概述：从 CEO 视角出发，讲述如何做好管理。

- 作者：Alex MacCaW，18 岁的 Alex 从高中辍学，放弃去哥伦比亚大学的机会，开始数字游民生活。后面创业做了估值 2.5 亿美金的 B2B 营销 SaaS 工具 Clearbit。

**** 内容
#+BEGIN_QUOTE
我们都需要一套自己的：项目管理 + 信息管理 + 关系维护的体系。
#+END_QUOTE

***** 个人管理
- 时间管理：观察自己的一天，将日历等工具充分用好，复盘自己的时间是否用在了高 ROI 上；
- 事务执行：坚持把事情做好，如开会要准时，会议要精简；
- 工具辅助：从事创意工作的人们如果经常被打断工作节奏？通过 GTD 管理好对应的任务优先级。真有拖延，考虑屏幕时间等工具来强制限制；
- 寻找导师：要知道伟大的运动员背后都有一个教练，个人也可以有一个教练。可以付费咨询，也可以找到周围能交换自我不安全意识的三两好友，定期请他们喝咖啡，从他人视角发现自我问题与找到解决方案；
- 识别弱点：要诚实的找到自己恐惧的点，尝试主动去突破这个恐惧，训练自己在逆境中保持冷静，摆脱情绪上的痛苦。
- 心理健康：知晓习惯的养成机制，确保有效的锻炼时间、吃的健康与睡眠充足。以及当代人最困难的点，脱离手机等电子设备的干扰。
- 感恩欣赏：定期感恩，让大家专注生活重要的事情、重视的事情，而不是负面情绪。如有可能，书面的夸赞很有必要。

***** 团队管理
- 招聘准备：拥有雇佣和留住人才的能力，招聘过程中尝试标准化招聘流程，理解自己现在需要什么，未来需要什么，考虑新成员带来的价值系数，不要刻意追求完美候选人。推荐看《Who: The A Method for Hiring》
- 面试：制定一套候选人筛选策略，评分机制等等，除了常见的将候选人答案作为锚点挖掘更多的问题外，其中两个点比较有意思，一是：及时纠偏话题，二是：让候选人针对自己的过去、现在、未来做比较。
- 目标管理：明确目标清晰、计划清晰与责任清晰。简化 OKR，从使命、战略、目标、关键结果帮团队摆正方向。
- 团队合作：如何开有效的会议，做正确的角色，以及管理远程团队。
- One One：一对一聊天的形式能够建立关系、共享信息，帮助团队成员发现问题，找到目标等等。文中的举例很有趣，一对一其实就是公司的免疫系统，协助发现问题。
- 绩效评估：利用 Gallup 提供的 12 个问题来跟踪了解团队成员。如有必要，可以使用 PIP 体系跟进绩效不佳的团队成员；
- 信息共享：对沟通内容进行详细划分，不同工具有不同的职能；二是对于信任建立的基础是处处透明；三是善用文档来进行沉淀，很喜欢这句话，大脑是承载想法，而非储存想法；四是明确团队成员职责范围。
- 面对冲突：一是明确什么是好的冲突，为冲突设置规则，引导大家清晰、有逻辑的表达问题与立场；二是针对现实风险进行分类，采取不同的方式解决问题。比如人际关系问题的解决应当是双赢，而非打压一方。

**** 如何精简的表达清楚一个问题？
表达观点的目的是什么？说服他人还是希望获得他人的认可，还是交换意见。虽然有 5W2H 的框架供参考，但是每次都抡起这一套，问题表达清楚了，但是时间也浪费了。我尝试根据自己所见所闻写了一些：

1. 目的：开门见山说清楚目的，要做什么？实现什么？
2. 背景：简单就是人、事、物。描述清楚是谁做了什么事情导致了什么后果；
3. 收益：实现这个目的对你我的好处是什么，有价值的驱动他人。

不过我想了自己的问题，让自己难受的不是没有框架，是没有主动，框架只是辅助表达的一个环节，迈出这一步才重要。现实生活就是这样，自信与挫败感相辅相成，让人烦恼。所以，主动一点，表达得体一些，也许就不那么烦恼了。

**** 事务优先级如何区分？
一个产品势必会收到来自四面八方的需求，当你收到 KA 的需求时候，我们应该如何划分优先级？我的想法是从以下几个方面：

- 战略视角：结合产品现在的状态，一般分为：萌芽期、成长期、成熟期，以及衰退期。在不同时期的战略侧重点不同，比如萌芽期大概率不能做出大规模推广的决策；
- 收益视角：即所做的需求能映射到用户身上的价值有多少，有时候改动一个按钮，满足大部分 KA 的需求，就可以很好的为其他迭代留出空间；
- 团队视角：团队成员人力情况、旧的技术债务影响；
- 产品视角：是否与当前迭代目标相契合。

说来说去还是 ROI，通过不断的条件拟合，得到有效的 ROI 预测来辅助决策。

对了，现实场景中还有 Leader 的判断，因为资源在 Leader 手里。如果 Leader 能合理看清楚团队的现状，合理分配资源，那么事务优先级划分的压力就传导到他的身上。

**** 备注

***** ROI

投资报酬率（return on investment，简称 ROI），经济学名词，指投资后所得的收益与成本间的百分比率。

投资报酬率一般可分为总报酬率（持有期间报酬率）和年报酬率。总报酬率是不论资金投入时间，直接计算总共的报酬率，亦即：总报酬率 = 利润/投入成本。

***** GTD

Getting Things Done (GTD) ，或译尽管去做，是由 David Allen 开发并发表在同名书中的个人生产力系统。在该著作中， 作者将该概念描述为时间管理系统，并指出若与一个任务（相关的念头停留）在一个人的脑海中，它将可能会完全填满其思绪，这将使得该人无法处理其他任务。

GTD 方法的思想是将所有感兴趣的项目、相关信息、问题、任务和项目从外部记录下来，然后将它们分解为具有已知时间限制的可操作工作项目。这使人们可以将注意力集中在对外部记录中列出的每项任务采取行动上，而不是凭直觉回忆它们。

***** 5w2h 原则

在设计新产品、面对事情、处理问题时，常常提出：为什么（Why）；做什么（What）；何人做（Who）；何时（When）；何地（Where）；如何（How）；多少（How much）。

这就构成了 5W2H 法的总框架。

以下为 5W:

1. WHY —— 为什么？为什么要这么做？理由何在？原因是什么？

2. WHAT —— 是什么？目的是什么？做什么工作？

3. WHO —— 谁？由谁来承担？谁来完成？谁负责？

4. WHEN —— 何时？什么时间完成？什么时机最适宜？

5. WHERE —— 何处？在哪里做？从哪里入手？

以下为 2H:

1. HOW —— 怎么做？如何提高效率？如何实施？方法怎样？

2. HOW MUCH —— 多少？做到什么程度？数量如何？质量水平如何？费用产出如何？

