#+title: 2022 年 1 月随笔
#+AUTHOR: panshishuo
#+date: <2022-01-04 09:00>

***** 随想
- 吵架：吵架时，是我们 vs 问题，而不是你 vs 我。
- 把小事捂成大事然后集中力量办大事，把大事弄成变事然后把丧事办成喜事。
- 成功（投资）的品质：耐心、毅力、知识、诚实、提前计划和纪律。
- 给我们有太多时间压力，自然会减少我们的选择权。这种坏习惯积累久了，会有一天把自己置于没有任何选择的地步，从而造成无法挽回的重大损失。
- 如果你做事的动机是为了获得别人的认可、证明自己才是对的 —— 那我劝你少做这样的事情，因为大多数情况下得不偿失。

***** 中下层内循环

其实打击教培，弱化高考竞争这些事情整体来说还是增加上升通道的，尤其是从底层到中层的上升。因为大城市的优势就是随处可见的补习班以及对应试的针对性培养。这样的结果就是「原生水平」比较高的底层，容易被大城市的中产小孩给卷下去了。

因为说到底，高考的蛋糕就那么大总有那么一批人上好大学，一批人上不那么好的。是增加还是降低阶层流动。就看各个阶层的家庭能够多大程度上把自己家庭的力量加成到下一代身上。现在是在不断的阻碍和打断这种加成的渠道，那么可以认为是利好底层，利空中层的。知乎上对这些措施整体上的负面评价可能是因为知乎的用户中现在或者未来的中产阶级比较多，文化水平和教育水平较高，而这些改革对这个阶层整体来说是不利的。

不过这也不是多么新颖的手段，自从工业革命以来，不断的把中产卷入底层，然后吸收底层中的精华组成新中产，就是英国提高整体国民素质的方式。

***** 很多用户并不关心效率

一般用户会偏向于消费、娱乐类的产品。

大家不喜欢工具，也不在乎效率、生产力，最好是全自动的（比如头条），最好不动脑（比如抖音）……

这样子可以把时间用来热爱生活/浪费时间。

一堆设计师一起做头脑风暴、想产品创意，结果一般会更糟糕：脸上满是喜悦的泪水。

出乎一般人的想象，一多半设计师其实既没有同理心（不知道别人想什么），也缺乏创造力、想象力、好奇心，其实没什么创意。

同时设计师对怎么实现产品没有概念，多数点子没法落地。

另外很多设计师表达能力不行，说话没重点，特别耗费时间、

***** 如何吐槽
吐槽之前，先询问对方。

- 不知有没有心情听我吐槽几分钟？
- 能现在聊聊天吗？感觉不太好，想找人说说话。
- 有个事情挺难过的。有精力听我说说吗？
- 今天压力真好大，想找人吐槽一下。你有心情听我说说吗？
- 今天感觉好糟糕。我知道你最近也不太顺，不知道你还有精力陪我说说话吗？

***** 知识付费，有两句话很见血

1. 那些知识付费所贩卖的知识速成，其实质卖的不是某一领域的知识，而是一种‘让你感觉很努力’的幻觉。

2. （很多）知识付费向用户兜售的，实质上是一种精神慰藉，让你感觉自己随时随地都能得到些什么有用的东西，从而有一种收获知识的满足感。

***** 一个女生对男朋友的 3 个忠告

一个女生对男朋友的 3 个忠告，非常感谢，铭刻于心：

1. 很多人有无数毛病，但都不足以致命，有人，一个就够了。所以我一直正视自己的缺点；
2. 永远不要让债务来找你，应该主动找他们，所以当我还不起债时，我就主动找债权人协商；
3. 记得爱人每天衣装，她失踪后，方便报警。

***** 钱能解决的问题就别麻烦别人
我自己也有需要朋友帮忙的时候，但扪心自问每次都有想过：

1. 有没有太麻烦别人了？
2. 能不能自己想办法不要麻烦别人就能解决？
3. 欠了这个人情以后怎么还？

结论是：钱能解决的问题就别麻烦别人。

***** 爱情原理
米兰·昆德拉在《生命中不能承受之轻》里不断强调这么一个爱情原理：“人类生命只有一次，我们不能测定我们的决策孰好孰坏，原因就是，在一个给定的情境中，我们只能作一个决定。我们没有被赐予第二次、第三次或第四次生命来比较各种各样的决断。”

其他选择也是一样，人生很难做“AB-Test”。

***** 认知的三个类型
广义的认知分为 3 个互相关联但不重合的部分

1. 知识论：是什么，为什么；

2. 认识论：我如何获取知识；

3. 教育：我如何让其他人获得这些知识。

中国教育以知识为中心，过分强调 1 甚至只是其子集“是什么”，导致部分家长辅导孩子的时候被气的七窍生烟“你怎么这么笨，这么简单的都不会”，其实更多是家长自己的问题。

德国的教育主要目的根本不在于获取知识，而是如何认识自己，发展自己，融入社会。例如：道德课讲的是什么是幸福、如何幸福、什么是民主、为什么要选举等等。授课的最重要原则是不能让任何一个人拉下学习进度（Inklusion)。

***** 读书的目的
如果一个人还为他没有犯过的错误去道歉、去讨好的话，那这种人什么事情做不出来啊？

读那么多书就是要在其中找出一个以后做人做事的道理，如果到头来还不能很勇敢的相信它的话，那做人有什么意思啊？

你要相信你的未来是可以由你自己的努力来决定的。

***** 傻逼陌生人搭话三步骤
傻逼陌生人搭话三步骤

1. 上来就问你工作、家庭、生活、收入

2. 羡慕语气夸一夸你，例如工作稳定，有拼劲儿，社会需要你这样的人才

3. 虚伪自谦，例如 “我做点小生意，累死累活一年挣不了几百万，羡慕你们坐办公室的”

瞬间爆炸，完成装逼

***** 智慧的五大标志
1. 不羞于承认自己理解有错。

2. 从犯错中吸取教训。

3. 不因为接受事实而感觉受到冒犯。

4. 适应能力超强，好奇心超强。

5. 知道自己有多无知。 ​​​​

***** 35 岁后的人生建议：搞钱
- 加强自己的学习力，接受新鲜事物的能力，不要自我脱离。
- 交流能力，语言表达能力，软实力。恰到好处的表达
- 利他能力，修炼自己，造福他人。

***** 如果你觉得祖国不好
如果你觉得祖国不好，你就去建设它；如果你觉得政府不好，你就去考公务员去做官；如果你觉得人民没素质，就从你开始做一个高素质的公民；如果你觉得同胞愚昧无知，就从你开始学习并改变身边的人，而不是一昧的谩骂，抱怨，逃离。

横眉冷对千夫指，俯首甘为孺子牛，“你所站立的地方，正是你的中国；你怎么样，中国便怎么样；你是什么，中国便是什么；你若光明，中国便不黑暗”。

愿中国青年都摆脱冷气，只是向上走，不必听自暴自弃者流的话。能做事的做事，能发声的发声。有一分热，发一分光，就像萤火虫一般，也可以在黑暗里发一点光，不必等候炬火。

此后如果没有炬火，我们便是唯一的光。

— 摘自《人民日报》。

***** 办事的顺序
在中国，最重要是原则，而不是规则。

按规则办事，但违反了原则，还是会很糟糕。

按原则办事，即使违反了规则，不会很严重。 ​​​​

***** 决不滥读书
我们读书之前应谨记“决不滥读”的原则，不滥读有方法可循，就是不论何时凡为大多数读者所欢迎的书，切勿贸然拿来读。例如正享盛名，或者在一年中发行了数版的书籍都是，不管它属于政治、宗教，还是小说、诗歌。你要知道，凡为愚者写作的人常会受大众欢迎。不如把宝贵的时间用来专读伟人已有定评的名著，只有这些书才是开卷有益的。

不读坏书，没有人会责难你，好书读得多，也不会引起非议。坏书犹如毒药，足以伤害心神。因为一般人通常只读新出版的书，而无暇阅读前贤的睿智作品，所以连作者也仅停滞在流行思想的	小范围中，我们的时代就这样在	自己所设的泥泞中越陷越没深了
