#+title: 2022 年 1 月随笔
#+AUTHOR: panshishuo
#+date: <2022-01-04 09:00>

***** 随想
- 吵架：吵架时，是我们 vs 问题，而不是你 vs 我。
- 把小事捂成大事然后集中力量办大事，把大事弄成变事然后把丧事办成喜事。
- 成功（投资）的品质：耐心、毅力、知识、诚实、提前计划和纪律。
- 给我们有太多时间压力，自然会减少我们的选择权。这种坏习惯积累久了，会有一天把自己置于没有任何选择的地步，从而造成无法挽回的重大损失。

***** 命运的三个转折点
命运有三个转折点：

1. 原生家庭；
2. 夫妻伴侣；
3. 觉醒的自己。

若没有优越的家庭，如意的伴侣，就一定要唤醒那个强大的自己重新洗牌。

***** 钱能解决的问题就别麻烦别人
我自己也有需要朋友帮忙的时候，但扪心自问每次都有想过：

1. 有没有太麻烦别人了？
2. 能不能自己想办法不要麻烦别人就能解决？
3. 欠了这个人情以后怎么还？

结论是：钱能解决的问题就别麻烦别人。

***** 爱情原理
米兰·昆德拉在《生命中不能承受之轻》里不断强调这么一个爱情原理：“人类生命只有一次，我们不能测定我们的决策孰好孰坏，原因就是，在一个给定的情境中，我们只能作一个决定。我们没有被赐予第二次、第三次或第四次生命来比较各种各样的决断。”

其他选择也是一样，人生很难做“AB-Test”。

***** 认知的三个类型
广义的认知分为 3 个互相关联但不重合的部分

1. 知识论：是什么，为什么；

2. 认识论：我如何获取知识；

3. 教育：我如何让其他人获得这些知识。

中国教育以知识为中心，过分强调 1 甚至只是其子集“是什么”，导致部分家长辅导孩子的时候被气的七窍生烟“你怎么这么笨，这么简单的都不会”，其实更多是家长自己的问题。

德国的教育主要目的根本不在于获取知识，而是如何认识自己，发展自己，融入社会。例如：道德课讲的是什么是幸福、如何幸福、什么是民主、为什么要选举等等。授课的最重要原则是不能让任何一个人拉下学习进度（Inklusion)。

***** 读书的目的
如果一个人还为他没有犯过的错误去道歉、去讨好的话，那这种人什么事情做不出来啊？

读那么多书就是要在其中找出一个以后做人做事的道理，如果到头来还不能很勇敢的相信它的话，那做人有什么意思啊？

你要相信你的未来是可以由你自己的努力来决定的。

***** 路径依赖
路径依赖绝大部分时候是不自知的，比如一个靠做题混起来的人会不断肯定做题的意义，可笑的地方在于你并不能因此而反驳，因为这样的人已经因此而获益了，他们并没错。问题在于，你也跟着这么干未必正确。

这很见鬼，但确实存在：对方没错，可你未必能跟着干。这也是警醒各种成功学经验的关键点。

最蛋疼的是，在走通你自己的路之前，根本分不清哪些路走得通、哪些路走不通，哪怕指路的仙人们都是真诚得想帮你，也不一定能沿着他们的路走下去，最后多半还是凭运气。

***** 傻逼陌生人搭话三步骤
傻逼陌生人搭话三步骤

1. 上来就问你工作、家庭、生活、收入

2. 羡慕语气夸一夸你，例如工作稳定，有拼劲儿，社会需要你这样的人才

3. 虚伪自谦，例如 “我做点小生意，累死累活一年挣不了几百万，羡慕你们坐办公室的”

瞬间爆炸，完成装逼

***** 智慧的五大标志
1. 不羞于承认自己理解有错。

2. 从犯错中吸取教训。

3. 不因为接受事实而感觉受到冒犯。

4. 适应能力超强，好奇心超强。

5. 知道自己有多无知。 ​​​​

***** 35 岁后的人生建议：搞钱
- 加强自己的学习力，接受新鲜事物的能力，不要自我脱离。
- 交流能力，语言表达能力，软实力。恰到好处的表达
- 利他能力，修炼自己，造福他人。

***** 如果你觉得祖国不好
如果你觉得祖国不好，你就去建设它；如果你觉得政府不好，你就去考公务员去做官；如果你觉得人民没素质，就从你开始做一个高素质的公民；如果你觉得同胞愚昧无知，就从你开始学习并改变身边的人，而不是一昧的谩骂，抱怨，逃离。

横眉冷对千夫指，俯首甘为孺子牛，“你所站立的地方，正是你的中国；你怎么样，中国便怎么样；你是什么，中国便是什么；你若光明，中国便不黑暗”。

愿中国青年都摆脱冷气，只是向上走，不必听自暴自弃者流的话。能做事的做事，能发声的发声。有一分热，发一分光，就像萤火虫一般，也可以在黑暗里发一点光，不必等候炬火。

此后如果没有炬火，我们便是唯一的光。

— 摘自《人民日报》。

***** 办事的顺序
在中国，最重要是原则，而不是规则。

按规则办事，但违反了原则，还是会很糟糕。

按原则办事，即使违反了规则，不会很严重。 ​​​​

***** 决不滥读书
我们读书之前应谨记“决不滥读”的原则，不滥读有方法可循，就是不论何时凡为大多数读者所欢迎的书，切勿贸然拿来读。例如正享盛名，或者在一年中发行了数版的书籍都是，不管它属于政治、宗教，还是小说、诗歌。你要知道，凡为愚者写作的人常会受大众欢迎。不如把宝贵的时间用来专读伟人已有定评的名著，只有这些书才是开卷有益的。

不读坏书，没有人会责难你，好书读得多，也不会引起非议。坏书犹如毒药，足以伤害心神。因为一般人通常只读新出版的书，而无暇阅读前贤的睿智作品，所以连作者也仅停滞在流行思想的	小范围中，我们的时代就这样在	自己所设的泥泞中越陷越没深了
