#+title: 日程管理思考和软件推荐
#+AUTHOR: panshishuo
#+date: <2021-12-31 06:09>

***** 不能靠自律去做事情

靠自律去做事情，太难了，必须习惯才可以或者有人去强制做事情：

对于习惯性的事情，自己可以坚持个一两周就会有一个类似“惯性”的驱动力去让自己做，还有就是要坚持做一件事情，这件事情在习惯的基础上必须要“容易做”、“方便做”：容易做是指有好的技巧和方式，自己在做这个事情本身的时候，抵触心理、操作难度要降低；方便做是指去做这件事的障碍小，比如你写笔记，最好就是手机、电脑、网页等都可以同步和编辑的工具。

有人强制，这个指的是，有人逼着你做或者流程上你必须做，通过规则去保证结果的一致性，减少犯错、避免犯错。这种更适应公共事业、集体生活和商业活动。

***** 笔记日程管理的思考

以前我们提及日程管理，都是在说 GTD，现在各种应用做笔记多倒是多，但是却走向了“邪路”：已经上升到“方法论”、“术”、甚至到了玄学的境地。

Orgmode、子弹笔记、日程笔记（Agenda/NotePlan）、大纲笔记（幕布/Workflowy）、Block笔记（Notion/超级笔记）、卡片笔记（Roam/Obsidian）、双向链接，以及诸多几个大写字母的简写理论，总之就是“成功案例 → ‘科学’理论 → 创造产品 + 布道 + 信仰”（或者反过来），其实又走了一遍曾经的 GTD 软件大战，折腾、玄乎。

科学的东西也是挑受体的，希望大家不要忘了做笔记的初衷，被工具乱眼，适合自己的工具才是最好的工具。

诚然每个人需要去记录和管理自己的生活，但是不必追求于工具本身，找到合适自己的工具就是最好的，就像条条大路通罗马，我们要知道的是自己要的罗马在哪里、怎么去，而不是纠结于同一类型的交通工具用哪个最好，要记住的一点是：每一次更换交通工具，都是有时间成本和精力损耗，不必舍本逐末。

***** 为什么用纯文本写作？

纯文本写作的好处：

- 通用，所有设备支持；
- 不过时，软件更迭但纯文本永存；
- 离线，不需要网络；
- 不依赖某个软件；
- 易转换成其他格式；
- 易分类，可以按需建立文件系统；
- 你不一定需要脑图。

可靠/易用/通用/独立/永存，纯文本在数百年后依然可读。

***** 如何每天高效工作

今天早晨看了一个视频有提到，《如何每天高效工作》，其实很多看似每天的计划，其实是可以提前安排的，有一些还是周期性的。

内容如下：

1. 有序的桌面效率更高：整理好桌子上的东西，分门别类，随用随取，不用花时间去找；

2. 桌面摆有限的三五个“玩具”：不宜过多，选择最喜欢的几个手办、玩具、乐高……，放在桌面即可；

3. 举目可见的 GTD 便签：整理每天的待办事项，并按优先级用从高到低贴在自己举目可见的地方，比如电脑的侧边；

4. 今日事今日毕：列出的便签的事情“必须”今日做完，所以不必列太多，反而徒增压力和焦虑感；

5. 使用番茄钟提高自己的专注力：可以设置一个固定时间的番茄钟， 30 分钟左右即可，每个番茄钟之间休息 5 分钟，番茄钟期间要专心的去做自己的事情，任务大的话，可以消耗多个番茄钟。

***** 笔记工具推荐

- [[https://flomoapp.com][不擅长做 灵感收集，推荐 浮墨笔记]]
- [[https://shimo.im][不擅长写 文档撰写，推荐 石墨文档]]
- [[https://www.yinxiang.com][不擅长做 文档收藏，推荐 印象笔记]]
- [[https://www.dida365.com][不擅长做 计划管理，推荐 滴答清单（TODO）]]
- [[https://www.xmind.cn][不擅长做 思维导图，推荐 XMind]]
- [[http://www.ankichina.net][不擅长做 助记卡片，推荐 Anki]]
- [[https://www.airtable.com][不擅长做 电子表格，推荐 Airtable]]

***** 工具推荐

- [[https://tiddlywiki.com/][TiddlyWiki]]
- [[https://logseq.com/][Logseq - A privacy-first, open-source knowledge base]]

***** 笔记工具比较

- [[https://www.noteapps.info/][笔记软件、笔记工具比较]]
