#+title: 如何成为一个更好的交谈者？
#+AUTHOR: panshishuo
#+date: <2022-02-07 09:00>

如何成为更好的沟通者，不浪费时间、不感觉无聊，以及最重要的是，不冒犯任何人。电台主持人 Celeste Headlee 在几十年的工作中，学到了许多沟通技巧，分享了 10 条提高谈话质量的建议，非常值得一看！

****** 1. 不要三心二意
处在当下，进入交谈那个情境中去。当你想退出就退出，而不是身在曹营心在汉。

****** 2. 不要好为人师
你需要在进入每一次交流时都假定自己可以学习到一些东西。真正的倾听需要把自己放在一边，有时候，这意味着把你的个人观点放在一边。

比尔·奈伊说：“每一个你将要见到的人都有你不知道的东西。”即每个人都是某方面的专家。

****** 3. 使用开放性的问题
关于这一点，请参考记者采访的提问方式，以“谁”、 “什么”。 “何时” “何地”、 “为什么”或“如何”开始提问。

****** 4. 顺其自然
也就是说，想法会自然流入你的头脑，而你需要将它们表达出来。

****** 5. 如果你不知道，你就说你不知道
要学着这样做，谨言慎行，谈话应该是负责任的行为。

****** 6. 不要把自己的经历和别人比较
任何经历都是独一无二的。而且，更重要的是，这不是在谈论你的事，你不需要在此刻证明你多么能干，或者你经受了多少痛苦。交谈不是用来推销自己的。

****** 7. 别重复自己的话
这很咄咄逼人，也很无聊，但我们很容易这样做，尤其是在工作交谈中，或者和孩子的交谈中。我们想声明一个观点，于是换着方式不停地说。别这样。

****** 8. 少说废话
说白了，没人在乎那些年份，名字，日期等等这些你努力试图在脑中回想的种种细节，别人不在乎。他们关注的是你，对方关心你是什么样的人，和你有什么共同点，所以忘掉细节吧，别管它们。

****** 9. 认真倾听
这不是最后一条，但是 *最重要的一条* 。
真正注意听别人讲这很耗费精力，但如果你不这么做，你们就不是在交谈，只不过是两个人在同一个地方彼此嚷嚷毫不相关的话。你们必须相互倾听，史蒂芬·柯维对此有精彩的论述：“我们大多数人都不是为了理解而倾听，我们为了回应而听。”

****** 10. 简明扼要
“好的交谈就像恰到好处的迷你裙:足够短，能够吸引人，又足够长，能够包纳(盖住)主体”
