#+title: 国男 PUA 几大话术
#+AUTHOR: panshishuo
#+date: <2022-02-20 00:01>

***** 立牌坊，戴高帽子，道德绑架

比如“好女人就应该生三个孩子，做家务，孝顺公婆”，”好女人就应该共同经营爱情，而不是拿生小孩作为筹码“，”你向我要礼物，太物质了“。

意思就是你要让他们占便宜，就给你一个牌坊（除此之外什么也没有），你不给他们占便宜，就是拜金婊子，往你身上泼脏水。

类似的还有，女生就应该 18 岁嫁人，女博士嫁不出去没人要。说得好听，但是那些所谓的”好女人“得到了什么？任劳任怨做家务生小孩，老公出轨的不要太多，家庭主妇老公出轨以后还没有经济大权只能默默忍受。

给女生洗脑，告诉女生人生最大的成就是给男的奉献一生，而不是有自己的成就和人生，不如“不生小孩不结婚的女人是不完整的”。很多国男话里话外会这样告诉你，男生一旦说了这种话就应该立刻拉黑。

***** 画大饼

不给女生实际的付出，用口头承诺来换取女生的实际付出。比如“你先给我付房租/买 xx /给艹，等我牛逼了我就给你 xxxxx”。

吹的很好听，但是一个人有没有诚意要看他的实际行动和付出，而不是口头吹牛逼。就算是学生或者刚工作没钱，他给你他现在的水平应有的待遇了吗？一个愿意请你吃食堂的男大学生，比十个嘴上说要给你买房买车但实际不送任何礼物的工作人士要更有诚意。

很多女生总想着以小博大，自己去倒贴那些有钱成功的人就能捞个大的，实际上最后都是被白嫖。

***** 否认男女之间的差异，忽视女性的弱势，要求所谓“平等”

比如开房上床，明明绝大部分情况下是男性占便宜，还舔着个脸说“房费要AA““女生也爽到了”。绝大部分性行为都是为了满足男性的欲望，男性也不会体谅女性的感受，也不顾女性性行为的患病风险更高。我觉得只有男的每插一下女的，女的也拿假jj插一下男的，才是真的平等，毕竟前列腺高潮男的也爽到了

比如女性生小孩，对肉体是巨大的损伤和痛苦，对个人职业发展也是很大的影响，男的还要说“你生小孩是为我生吗？”，就算生小孩是男女共同的目标，女性难道不是付出更多吗？

比如工作的人和学生 AA，占学生的便宜。

***** PUA，压价，告诉你你不配

比如说，“现在去嫖一次才几百几千，为什么要结婚？”首先现在北上 ww 一次至少 2w。其次，结婚了女的要给男的做家务，生娃带娃，收益平均下来其实还不如五千一晚的 🐔 。去年有个新闻，上海全职太太三年生娃做家务，离婚只判 5 万家务补偿费，平均下来就是 1400 一个月。

其次，“为什么你比我年轻/漂亮我就要多付出？”，男的既看不起和打压大龄/不好看的女性，又想白嫖年轻漂亮女性，这种直接让他滚。

“你的择偶条件太高了，你也想找这种高学历/富二代/xxxx，你配吗？”说实话大部分人对高学历、富二代有不切实际的幻想，比如皇帝一定用金锄头，然后用自己的幻想来打压你。说实话我也接触过不少 HYPSM /家产八九位数/厅级以上的男生，其实他们真的没那么挑，反而是 985 做题家更 picky。

“你长得漂亮不值钱，我是 985 我才值钱”。中戏北电的女生去饭局，就陪人吃饭什么都不做，一顿饭大概是 2 万。微博小红书粉丝十万的网红，接一个推广大概是 1-3 万。另外，价值是由市场决定的，男的为什么要一边追求美女一边说美女不值钱呢？就是想压价啊。

另外，中国男比女多三千万，因为长期以来对女性的打压和歧视，女性更难有高收入高学历。女性找学历和工作比自己强的男性其实是平配。

***** 躺平威胁

“你们国女再打女权我们国男就不结婚了！看谁急！”“我们国男都去找外国女生了，不找国女”

女生本来就应该做好不结婚不靠男人也能活的准备，如果你发现不结婚就活不了，就想想是不是哪里出了问腿，比如你是不是在一个没有任何社会福利保障并且歧视女性的国家？这时候就不要浪费时间关心男的怎么想了，赶紧”润“！

***** 否定和攻击女性的文化和特质

比如“头发长见识短”，这种毫无逻辑的。

还有“女生整天想着买包，很肤浅”，请问男生整天想着买游戏显卡相机车，就是高大上了吗？买包的女生就一定肤浅吗？这个问题就像，玩游戏的男生就一定不务正业游手好闲吗？仔细用脑子想一下就会发现是 PUA。

还有”女生没办法做 xxxx，这些工作都是男生在做“。其实很多工作男多女少并不是女性不适合，而是系统性对女生的歧视，比如从小 pua 女生不适合学理科，比如土木机械航天行业很多单位招聘“只要男生”。在美国有很多女警察，女装修工，女航天员，我在纽约的朋友就是做土木的，曼哈顿 200 米高的楼就是她画图纸，在工地上监工。

***** 把自己包装成受害者

比如舔狗，这个词已经被滥用了，一开始舔狗是指男生单方面付出，现在男生没有付出也可以叫舔狗了。天天微信骚扰女生，说一些女生不喜欢听的话，还道德绑架要求女生一定要回，这就是舔狗吗？

以前是男生为女生做了很多事，女生不喜欢他，叫舔狗；现在男生只是口头对女生骚两句，女生不回他，就是舔狗了；将来女的只要不千里送 bi，倒贴嫁妆，男的就是舔狗。

再比如反对杨笠的普信男，普信男原意是指 condescending，而且会去攻击和骚扰别人，让人感到不适的男性。这种男性在生活中实在太多了，所以引起很大反响，并不是对全体男性的攻击。

比如男性已经明明在从小到大的教育，成长，财产分配上很占便宜了，还要说社会优待女性，择偶优待女性。湾区男生找不到女朋友，有没有想过为什么女码农少？是因为女的不想当码农吗？不，是因为女的从小被 pua 不适合理工科，被打压自信，在职场上被歧视，所以更少的机会去学计算机也更不倾向于学。是因为社会价值观告诉女的自己努力工作不如嫁个好男人有用。是因为重男轻女，家庭不愿意把财产给女性，投资女儿上学。
