#+title: 2022 年 2 月随笔
#+AUTHOR: panshishuo
#+date: <2022-02-01 00:01>

***** 随想
- 一个人对与人交往的爱好程度，跟他的智力的平庸及思想的贫乏成正比。人们在这个世界上要么选择独处，要么选择庸俗，除此以外再没有更多别的选择了。

***** 格局
最近很喜欢一段话：欲成大树，莫与草争；将军有剑，不斩草蝇；遇烂人及时止损；遇烂事及时抽身。格局小的人，喜欢诋毁和嫉妒，我不好我也不能让你好。

格局大的人都懂得一个道理：强者互帮，弱者互撕。人性最大的愚蠢就是相互为难，人活着发自己的光就好，何必吹灭别人的灯。

***** 安全感和童年

人生总是要被打脸的。我宁愿在小时候被温暖，长大了再被社会打脸，也不愿意小时候就被打脸，长大了才被温暖。

因为这两种人生的感受是完全不同的。前者的默认状态就是自信、乐观、好奇、开心的，ta 认为这个世界总体上是安全的，因此可以去探索、去尝试；ta 对别人抱有一种善意假设，除非已经有了劣迹，不然总是愿意交往看看;ta觉得自己有能力，可以改造世界，使自己生活得更好，使世界也变得更好。虽然长大以后，会历经各种打击，使得 ta 对世界的看法越来越客观，但 ta 一辈子的心理底色，都是明亮的。

相反，后者的默认状态是焦虑、迷茫、担忧、怨恨的，ta 的大脑已经被小时候的经历训练为“这个世界危机四伏，我的第一要务是保护自己”，因此对别人经常是恶意假设，“总有刁民要害朕”；对自己不够有信心，总在担心别人对自己的评价，就怕自己不能满足别人的期望，或者被别人看不起，也不太敢去探索世界。当然，ta 会慢慢地发现，其实世界没有那么可怕，别人没有那么坏，自己其实也是有能力、值得被爱的，但 ta 一辈子的心理底色，都是阴郁的。

***** 请友善待人
请友善待人，因为你不一定了解：
1. 对方的过去；
2. 对方的想法；
3. 对方的创伤；
4. 对方的烦恼；
5. 对方的焦虑；
6. 对方的抑郁；
7. 对方的孤独寂寞；
8. 对方的脆弱不安；
9. 对方的自杀倾向。

***** 为什么 30 不是新的 20
（梅格·杰伊）

大意：

我们 20 多岁是成人发展的关键时期；
要成就大事，你需要一个计划，而不是足够的时间；
在我们 30 多岁的时候一次完成所有事情会更加困难和压力更大。

三个建议：
1. 不要沉陷于身份危机，要努力获取并积累身份资本；
2. 跳出熟悉的朋友圈，善于利用弱关系；
3. 现在开始选择伴侣，组建有爱的家庭：家庭关系好不好真的能决定一个人的一生；

结论：
这就是我现在有幸每天对像艾玛这样的 20 多岁的人说的话：30 岁不是新的 20 岁，所以，申领你的成年，获得一些身份资本，利用你的弱关系，选择你的家庭。 不要被你不知道或没有做过的事情所定义。 你现在正在决定你的生活。

***** 稻盛和夫：勤劳根本不能致富

勤劳根本不能致富，当今社会信息产量过剩，努力和回报根本没有因果关系，盲目的努力是在消耗生命。

做事讲究的是效率，而非你付出的多少，请不要用勤劳来掩饰你的不动脑，认知、资源、方法、选择，比努力更重要。

很多人输在了不是不够努力，而是输在了盲目努力和傻傻坚持上，你要抬头看路，而非低头干活！

***** 五年计划

我们站在现在看，自己为五年前的目标和计划做了些什么、完成了这些目标和计划吗？我们现在又在为五年后的目标和计划，做了什么。

任何时间想做事，都不晚；

一些事情，现在不做，以后总要付出更大的代价去做。

***** 性爱与婚姻

性是一种自然的人类需要，就像食物和饮料一样。

性欲正同食欲是一样的。愈是节制，欲望就愈高；反过来，欲望满足了，它就会暂时消解。而当性欲急切时，它会把一切都从人类精神范围之内排挤出去。

罗素 《性爱与婚姻》

***** 被拐的流程

最近好多妇女被拐的事儿被浮出水面我发现很多女人压根不是神经病人贩子流程:

```
拐走 --> 下药 --> 轮奸 --> 暴打 --> 轮奸 --> 虐待 --> 轮奸 --> 关押 --> 卖一手 --> 生娃 --> 卖二手 --> 虐待生娃 --> 女的疯了
```

我想请所有正常女人假想一下：

如果是你，下班路上被一麻袋拖到车里经历了这些，你会在第几个流程疯？疯了就好控制了，沦为生育的母猪。

我不知道原来这么多，这么惨。人间地狱。

这种事就是你万一倒霉，就一辈子消失在人海连发微博警示大家的机会都没有了。

***** 原来的配方，熟悉的味道

徐州铁链女，武汉李文亮

第一篇通告：不存在拐卖；
第二篇通告：未发现拐卖；
第三篇通告：不排除拐卖；
第四篇通报：涉嫌非法拘禁。

原来的配方，熟悉的味道：

第一篇公布：不会人传人；
第二篇公布：未发现人传人；
第三篇公布：不排除人传人；
第四篇公布：发现个别人传人。

***** 想做什么，立刻就去做

想做什么，立刻就去做！

20 岁时，你要得起你 10 多岁时想要的零食，却没有了当初的那般期待感。
30 岁时，鼓起勇气去追 20 岁时不敢追的姑娘，可姑娘早已嫁为人妻。
40 岁时，你再想去买 20 岁时买不起的球鞋，可你早已不再年轻。

人生就是这样，错过了，你就再也回不来了，有些事情你现在不做，你以后也做不了了。
