#+title: 聪明的自私与愚蠢的自私
#+AUTHOR: panshishuo
#+date: <2022-03-03 09:00>

靠得住的做法，还是把话说透，把账算清。其实，自私未必害人，也可能只是吝啬；损人也未必利己，也可能得不偿失。有“损人利己”，也有“利人利己”。把“利人”和“利己”对立起来，或者把“损人”和“利己”等同起来，恐怕都不科学。

***** 自私的分类

科学的方法，是把所有的选项都列出来，看看究竟有多少可能，多种可能：

人、己、利、损，排列组合，至少有以下这些选项 ———

　　一，毫不利己，专门利人；

　　二，毫不利人，专门利己；

　　三，为了利己，不惜损人；

　　四，只是利己，并不损人；

　　五，既不利人，也不利己；

　　六，既不损己，也不损人；

　　七，利人利己，人己两利；

　　八，害人害己，人己两害；

　　九，损了别人，没利自己；

　　十，毫不利己，专门害人。


***** 自私排行榜

我们可以做一个“排行榜”

　　最崇高：大公无私，毫不利己，专门利人。这是只有“圣人”才能做到的。我们可以推崇，可以向往，可以赞美，甚至可以提倡，但不能强求。因此这一选项，不妨作为少数人的追求。

　　最君子：一事当前，先利别人，后利自己。不是圣人也能做到，但需要境界。这种境界无关乎学问，也无关乎修养，说白了是一种人生态度，因此往往只有“一念之差”。

　　最感人：关键时刻，牺牲自己，帮助别人。不是圣人也能做到，但需要爱心。比如做母亲的，在危难时刻，往往会“本能”地挺身而出，牺牲自己，保护孩子。

　　最聪明：利人利己，人己两利，互利双赢。不是圣人也能做到，但需要智慧，也需要信念，即相信人与人是可以和谐相处、互助互爱的。实际上，不损人则仁，能利己则智。互利双赢，可谓“仁智双全”，值得提倡。

　　最保险：只是利己，并不损人。

　　最本分：既不损己，也不损人。

　　最消极：既不利人，也不利己。

　　最自私：毫不利人，专门利己。以上四种，不需要智慧，也不需要境界，还不需要信念和爱心，任何人都能做到。格调虽然不高，但于社会无害，应该宽容。

　　最卑劣：为了利己，不惜损人。这是社会公害，必须坚决反对。

　　最愚蠢：损了别人，没利自己。傻瓜才这么做。

　　最混蛋：害人害己，人己两害。可谓丧心病狂。

　　最恐怖：毫不利己，专门害人。为什么这个最恐怖？因为有“道德光环”，并不容易识破，却很容易获得同情，我们不能不提高警惕，倍加小心。

***** 何去何从？

所有的账，现在都算清楚了。何去何从，诸位三思。
