#+title: 2022 年 3 月随笔
#+AUTHOR: panshishuo
#+date: <2022-03-03 00:01>

***** 随想
- 别人谈恋爱很容易，认识个人就直接坠入爱河，没过多长时间居然订婚了，你是又惊又羡慕，反观自己，磨磨蹭蹭，这样不行，那样不行，遇到的人反正就是没感觉，算了，承认吧，自己就是事多……
- “做自己，可能只有 100 个读者” vs “做别人，可能拥有 100 万读者”，我选第一种。
- 自制力从来不是要几点睡觉几点起床，自制力从来都是永远只做最重要的事。 自制 —— 可以牺牲掉所谓的计划、规划和作息规律，也要把对于你事业来说最重要的事情每天干完，且坚持多年。
- 有时候没有得到你想要的东西是一种奇妙的运气。
- 早上：我有一个绝妙的点子；中午：这里怎么这么难；下午：我知道为什么这东西没人做了。
- 效率博主不会告诉你，他们保持效率的终极诀窍是：至今仍然单身。当年意图“做大做强、闪电式增长/规模化扩张”的创业者，如今追求“做小而美、不融资、自我造血”的另一个秘密是：他们结婚成家了。
- 有 3 种人值得深交：1. 关心政治，胸怀天下目光远大的人；2. 体恤民生，善良正直，懂得生存艰难，活得有痛感的人；3. 成熟稳重，逻辑客观，脱离了低级趣味，有独立思考的人。
- 巴菲特给年轻人的三个建议：投资自己，强健身体，与智者同行。

***** 如何获得别人的尊重

想要获得别人的尊重，首先自己要有值得令人尊重的品格，例如：谦虚谨慎、尊重他人、以理服人、负责、善良、认真、诚实，等等。

你希望别人怎样对待自己，你就应该怎样对待别人。

一个卑鄙小人，是永远不可能获得众人的尊重。

***** 悲伤与理智

历史学家会模糊你的焦点，其方式就是用你的愤怒来取代你的决心。实际上，你会想到 —— 至少我会这样想 —— “谁之罪”的问题整个儿都不过是白人的花招，旨在防止你作出某些情势所迫下的过激行为。

这也就是说，你在历史那里学到的东西越多，你在现实中的行动能力或许就越低。

***** 什么是真正的教育

没人强迫你接受新观点。如果你对少数族裔、同性婚姻、跨性别者、新移民，女性有意见，没人强迫你改变想法。 你只是没有权利用你的偏见去欺负别人。你没有权利把别人日常的生活变成你意识形态的战场。你没有权利用你的偏见，去压迫、骚扰、恐吓别人。

教育 ≠ 规训

规训：设置思想的边界，建造知识的围栏。
教育：打破边界，拆掉围栏。

规训 = 约束
教育 = 解放

请废除教育过程中的规训，让教育真正成为教育。

***** 没人教却很重要的能力

哪些能力没有人教但又特别重要？

1. 幽默；
2. 讲故事；
3. 管理财富；
4. 健康的心智；
5. 如何写一封 cold email。

***** 三八妇女节

3.8，希望女性首先都能是女人，不要被“铁链”所束缚，然后再谈是否可能快乐的事情，先说一声：三八妇女节快乐。

小时候我们的三八妇女节是真的妇女节，大家都会祝福老师和妈妈三八妇女节快乐，然后不知道什么时候妇女节没人提了，变成了女生节、仙女节，现在呢，变成了女神节、女王节，谁提妇女节好像就是跟这个时代作对一样、拉了历史的倒车一般，这对吗？这不对、这真的不对。

三八国际劳动妇女节，祝大家三八妇女节节日快乐。

2022.03.08

***** 六大发明

1. 象棋：中国政治象征，一切为了保帅。
2. 麻将：中国国民象征，互相算计，只为自己成功。
3. 围棋：中国思维象征，一切都是非白即黑。
4. 军棋：中国官场象征，官大一级压死人。
5. 杂技：中国现状的象征，折腾来折腾去其实都是为了维稳。
6. 武术：中国军事的象征，架式吓人，近期没见制服过谁。

***** 线上交流建议

1. 请确认您理解了对方的意思。
2. 您不必理睬每一个人。您不必回复每一条信息。
3. 请抱着学习的心态。
4. 如果发言，请尊重别人。
5. 避免与网暴者对话。
6. 如果对话让您身心俱疲，请立即停止。
7. 拉黑可能会对您带来物理伤害或精神伤害的人。
8. 在聊天中用助词或表情来表达语气。
9. 理解别人文字中的语气。
10. 公共平台发言之前，预估此平台的用户是否会欢迎您的言论。

***** 好的伴侣

1. 能为您匀出时间和精力。
2. 能考虑您的感受。
3. 不会打压你。
4. 做错时能向您道歉。
5. 能主动沟通。
6. 能给您提供支持。
7. 能尊重您独处的需求。
8. 会考虑您的意见。
9. 不歪曲事实。
10. 能讲清自己的需求。
11. 能表达爱意。
12. 会尊重您的边界。

****** 自学是门手艺

至少有 99% 的人终生没有掌握自学能力。绝大多数人，在有人教、有人带、有人逼的情况下，都没能真正把那些基础知识学明白。

更可怕的是，他们学的东西，绝大多数终其一生只有一个用处：考试。

真正的自学，进入社会才开始啊。

****** 我们可以去追求自己的幸福

世界本来就是不公平，怎么可能公平。你出生在农村，盖茨的孩子出生叫盖茨，家里面，你能比吗？但是有一点是公平的：比尔·盖茨一天 24小时，你一天也是 24 小时。

这 24 小时分 3 个 8 小时：

8 小时你在路上走，在挤公共汽车，在走路，你根本不知道自己在干什么，你这时需要好的朋友；

还有 8 小时你睡在床上，你也不知道自己在干什么，你这时候需要有一个好的床，床上有个好的人；

还有个 8 小时，你知道自己在干什么，那就是工作。假如你工作是不开心的，你做的事情你不爽的可以换，千万别做坐在这个工作，讨厌这份工作，我觉得这些人是没有意义。

所以我想每个人要清楚，世界不公平，出生的条件不一样，但是人是可以幸福的，你是幸福是自己去找的。

—— 马云

****** 也谈两种人

第一种人：

1. 学历：受过高等教育，注重继续学习；
2. 行事风格：按规则办事、谨慎、做事有边界、对未来风险有充分认知，有大局观、看重长远发展；
3. 三观：以人为本、更注重里子，不太注重别人的看法；
4. 对子女：注重子女教育，男孩女孩都一样；
5. 生活习惯：自律、注重健康、爱读书……；
6. 社交：社交关系简单、不抽烟，社交饮酒；
7. 思维模式：注重客观事实、逻辑、能独立思考，对事不对人。

另一种人：

1. 学历：没接受过高等教育；
2. 行事风格：讲究哥们义气，有点匪气、有事习惯找人私了，注重眼前利益，做事上头，不考虑后果；
3. 三观：好面子、生怕被人看不起，容易超额消费；
4. 对子女：子女教育依靠老人、重男轻女；
5. 生活习惯：自由、作息不准时、更喜欢刷手机……；
6. 社交：无效社交较多，抽烟喝酒，官本位思想严重；
7. 思维模式：满脑子都是立场和观点，缺乏独立思考能力，从众心理严重，对人不对事。
