#+title: 一些历史的演讲、发言
#+AUTHOR: panshishuo
#+date: <2020-01-01 08:57>

**** 站内内链
***** [[./mayunwaitan.org][马云上海外滩金融论坛演讲全文]]

**** 只言片语
***** 对安保的无节制投入，究竟在防谁？
清华大学劳东燕教授问：

对安保的无节制投入，究竟是要防谁，要保护谁，我是越来越困惑了。

我原本以为，自己应该是被保护的对象，但是在这样连番举措之下，我分明感觉到，自己就是被防空的对象。

还有完没完？

当下的各种安保措施，怎么看都是基于有推定的思维。

—— 防民如防贼，21 世纪了，不能这样了！

这个社会，若是还没有陷入被迫害妄想症的状态，就该在安保问题上适可而止。歇斯底里地追求安全，带给社会的，根本不是安全，而是全面的压制，还有恐慌。

***** 梁启超写给儿子梁思成的信
关于思成学业，我有点意见：

思成所学太专门了，我愿意你趁毕业后一两年分出点光阴多学些常识，选一两样关于自己娱乐的学问，如音乐、文学、美术等。

我怕你因所学太专门之故，把生活也弄成近于单调，太单调的生活容易厌倦、厌倦即为苦恼。

***** 话丑理端，句句在理
清华大学孙立平教授说，中国经济这 40 年是取得了巨大的发展，这是不可否认的，但是他不认为是奇迹，而是政府变卖的千年以来的土地，土地的价值本来就在那里，只不过是今天把它变现。

透支的未来百年的生态环境，现在和今后 100 年都要为过去的透支的环境来买单，而且这个单越来越贵，并不产生价值。

逃避了应该给农几亿民工应有的社保和各项其本福利的责任，让那些为中国建设付出一生岁月的几亿农民工，老无所养，病无所医，孩子在城里没有受教育的机会。

在国际上又利用 WTO 规则的漏洞，用国家补贴方式，将上述方式创造的价值在国际上变现，又成为国家外汇储备。

又用通货膨胀方式将老百姓手中的一点儿钱掠夺的一干二净，跟在政府后头的是一群精致的利已主业者，一群摸透高层心思的吃人豺狼，一群化妆成企业家的骗子，用金融创新，p2p，高息理财等等手段，再一次将中产阶级盘剥干净，除了还要按揭一辈子的的房子，其他一无所有，成了彻彻底底的房奴。

所以，你看到现在岁月静好的一群人，在全世界旅游，购买奢侈品的的游客占 14 亿人的比例。不过是几千万人，他们是退休的官员，大国企的员工，有编制事业单位的人员，和少数发了财的民企老板和高管及其亲属。

在当今的世界上，没有哪一个发达或者不发达国家，有如此不公平的福利分配制度。现在的问题是盛宴的末尾，酒没了。"

***** 一次巨大的失业浪潮，正在向我们涌来。
清华大学孙立平：一次巨大的失业浪潮，正在向我们涌来。

首先是陷于困境的房地产在大量裁员；

其二是外商外资企业纷纷撤离中国；

其三是中小企业的不景气、倒闭潮；

其四是教育双减引发的对于教培行业的整顿，波及千万人的生计；

最后是跨国电商的整顿，比如亚马逊平台整顿电商秩序，出现批量封店、封号情况，一批中国跨境电商巨头陷入困境。

应该想法解决自由工作的吃饭问题，如摆地摊，开网店等，如果没有工作的情况下，也能通过劳动获得的方法，这个目前很难，亟需有解决方向。

***** 共产主义五大理论
唯物论：把人物质化，人性物质化；

无神论:不信善恶有报 从而敢于无恶不作；

阶级论：人为区分阶级 制造社会矛盾，挑拨民众自相残杀；

辩证法：混淆是非善恶 颠覆伦理道德，使人放弃价值判断；

进化论：把自己归类于禽兽，接受从林法则，强者可以消灭弱者。

