#+title: 人民日报：不告密不揭发是道德底线
#+AUTHOR: panshishuo
#+date: <2021-12-23 09:00>

#+BEGIN_QUOTE
告密、不揭发，与其说是一种可贵品质，不如说是一条道德底线。告密成风的社会，是人人自危的社会，告密使人与人之间失去基本信任，甚至相互侵害，冲击人们的价值判断，毁掉社会的道德基础。
#+END_QUOTE

“我不知道，查理今天的缄默是对还是错，但我可以告诉你，他决不会出卖别人以求前程。而这，朋友们，就叫正直，也叫勇气，那才是领袖的要件！”

这段话，是美国电影《闻香识女人》中的一段台词。片中，查理无意间目睹了几个学生对校长的恶作剧，校长逼查理交代谁是主谋，否则将开除他的学籍。查理的忘年交、盲人史法兰，在听证会上谴责校方正在毁灭这个孩子纯真的灵魂。演讲博得如潮掌声，使校方最终作出让步。

“不出卖别人以求前程”，是正直，也是勇气。这不仅是为个人辩护，更是为一种优秀品质辩护。

一种风气的形成，有其历史土壤；而其消泯，更是难上加难。至今，这种“告密揭发”思维还时常作祟。据报道，山东某高校期末考试一道试题是：选出你认为上课最积极的3名同学和翘课最多的3名同学。考题一披露，网友直呼“神题”。

可以设想，那些写出“翘课最多”学生名字的考生，可以轻松得分；拒绝写出的，则不得不丢分。这不是在鼓励学生们相互揭发吗？

出题者辩解说，这是借鉴人力资源管理专业“360度绩效考核”中的“同事相互评价”。但是出这样的试题，未免把好经念歪了。学生翘课多少，自有学校纪律管束；学生的学习状况，也有考试成绩评定。即便学生间相互评价，也应该是当面锣对面鼓，积极公开的，而不是暗地里互相“揭发”。

无独有偶。几年前，湖北某大学的一个班级出台了“盯人”管理办法，每名学生的一言一行都会有一名“神秘同学”在暗中盯梢。班主任说，开展这项活动是为了加强学生间的友谊和互动，也是为了加强学风、班风建设。这样的“温情关怀”，简直让人不寒而栗。

心理学专家认为，不确定性会使人处于恐惧和焦虑的状态中。一个经常有人“打小报告”的班级，气氛一定紧张不安，同学间、师生间一定疏远而戒备。学生时代播下的不信任的种子，会影响他的一生。

不告密、不揭发，与其说是一种可贵品质，不如说是一条道德底线。告密成风的社会，是人人自危的社会，告密使人与人之间失去基本信任，甚至相互侵害，冲击人们的价值判断，毁掉社会的道德基础。

这条底线，在大学里首先应该明确、清晰起来。大学，应该培育学生自由而健全的人格、敢于担当的精神，让学生成为一个阳光磊落的大写的“人”，而不应该是心理幽暗、出卖他人的“病人”。这是大学精神的应有之义。

备注：

原标题：人民日报：不告密不揭发是道德底线，（[[http://opinion.people.com.cn/n/2015/0123/c1003-26435303.html][2015 年 1 月 23 日 12 版，人民日报，原题《“神题”侵害大学精神》]]）
