#+title: 2021 年 11 月随笔
#+AUTHOR: panshishuo
#+date: <2021-11-30 15:57>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="static/myStyle.css" />
#+HTML_HEAD_EXTRA: <meta charset="utf-8">
#+HTML_HEAD_EXTRA: <script async type="text/javascript" src="https://cdn.rawgit.com/mathjax/MathJax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

**** 随想
- 真正能缓解焦虑的，却是总想偷懒不做的事情。
- 一个人知道自己为什么而活，就可以忍受任何一种生活。
- 少女 > 儿童 > 少妇 > 老人 > 狗 > 男人，据说是投资消费领域的人总结出来的市场价值。
- 将个人处境归咎于原生家庭，往往是逃避的借口。
- 那些发财的路，并不是写在刑法里面，而是要跟着美联储和人行作对。它们发钱，你要买资产；它们收钱，你要守着钱。
- 每个成年人要为自己的行为负责，要有所为有所不为，不能随心所欲的想做什么就做什么。
- 朋友圈就算热情似火，人们最终还是会选择表现出冷漠。

**** 克服懦弱远比职业规划重要
一个人的人性，才是他人生的天花板。
绝大部分人的问题根本不是什么职业规划问题 —— 而是他们人性的丑恶和懦弱。至于说什么职业规划 —— 请问，给你规划了，你敢去做吗？

最好的职业规划，从来都是尊重本心，想做就去做，直面自己的欲望，直面所有面临的风险。能承受失败，才配得上成功。但是大部分人渴望的职业规划是 —— 零风险走向成功。
请问 —— 他们配吗？

凭什么他们家庭条件又差、学历又不好、人又怂，然后这个世界专门为他们准备一条路，可以零风险成功呢？对不起。没有这条路。如果有这条路，那就是骗你的。

解决方法是什么？先承担风险，才有可能有未来。
记住，承担风险，不一定有未来。但是不承担风险，永远没有未来。承担风险，可能是找死，但是不承担风险，是等死。如果是我，我宁愿找死也不等死。只不过大部分人 —— 宁愿等死，也不找死。

看过丧尸片么？当丧尸来的时候。所有想躲在房子里不跑等着别人来救的人，最后都死了。只有勇敢的跑出去的人，才有一线生机。你现在就是在房子里等死的人。

遭遇危机的社畜，这方便暴露的人性 —— 就是懦弱。不克服懦弱，一切规划都是扯淡。规划的第一要素并不是规划本身完不完美 —— 而是执行力。但是懦弱的人都没有执行力。因为执行需要风险，意淫没有风险。

**** 成事的四步：
1. 知道哪些可以做。
2. 判断什么最值得做。
3. 有魄力果断投入去做。
4. 有能力把事做成。
四点缺一不可。缺了任何一点都无法成事。所以成事很难。
第 2、3 两点看起来最没技术含量，却也是最多人欠缺的。
