#+title: 炒股书单推荐
#+AUTHOR: panshishuo
#+date: <2021-12-10 12:07>

炒股要赚钱没有捷径，只能多实践、多读书。但炒股书籍这里有个坑 —— 要读好书！

以我的阅读经验来说，炒股的烂书特别多。大概这几类：

1. 用自己狭隘、甚至错误的观念去写书，还特别言之凿凿，让人以为真理在握。这类炒股类图书作者多是交易员的背景，具有“工匠”的思维模式，自己手里有把锤子，看啥都是钉子。

2. 云山雾罩一大堆，说一吨的“正确的废话”，但就是不告诉你实操细节。这类书可以用缺乏“书德”来形容 —— 你要是不愿意给干货，为什么要出书？！

3. 给自己歌功颂德，为自己立牌坊写的书。这类书基本都可以归于垃圾。

***** 《winner take all》
一本比较冷门的小书，《winner take all》，作者是加拿大人 william gallacher。网上有中文版的 pdf，书名是《稳操胜算》。这书名的翻译太奇怪了，明明是“赢家通吃”，非要翻译成“稳操胜算”，莫名其妙。这书我看了三遍，它好就好在是一本说实话、有干货、有格局的书。

***** 《对冲之王：华尔街量化投资传奇》
这本书太好了，然后你会认为中文译者实在太恶心了。这书的中文名字是《对冲之王：华尔街量化投资传奇》，而原书的名称是《The Physics of Wall Street: A Brief History of Predicting the Unpredictable》（华尔街的物理学：对不可预测的预测简史）。中文书名翻译得太烂了，差点让我错过这本让我看了三遍的好书。这书的三位中文译者，真应该为自己感到羞愧！

***** 《漫步华尔街》
炒股不如投基金，赚钱还省心。

***** 《股票大作手回忆录》
交易员的“圣经”，人手一本。

***** 《投资最重要的事》
橡树资本的老大霍华德写的，这是他每年给股东投资信的合集，挺好的。

***** 《以交易为生》
关于如何交易，这是一本百科式的入门书，很适合新手。这书销量挺好的，后来作者又写了一本《以交易为生2：卖出的艺术》，也挺适合新手。

***** 《股市真规则》
晨星的分析师写的一本书，详细介绍了如何做“基本面分析”，基本都是干货的内容。

***** 《交易心理分析》
讨论交易时候心理状态的一本好书。

***** 《价值投资的十项核心原则：成为聪明投资者的工具与技巧》
行为经济学的一本好书，能带来智力上愉悦感，作者很幽默，写得好玩。

***** 《止损：如何克服贪婪和恐惧》
这是一个失败的交易员的肺腑之言，《黑天鹅》作者塔勒布强烈推荐的一本书。

***** 《cis 的股票交易术》
cis 是日本一个散户的昵称，他可能是日本最牛的散户之一。这本书主要讲了他的“趋势交易”操盘经历。

***** 《股票量化交易的 7 个策略》
这书可以说是纯干货了，直接给了 7 个策略和具体指标。作者 拉里·康纳斯 是一个资深交易员，他特别擅长使用 RSI 指标。

***** 《金融怪杰：华尔街的顶级交易员》
17 个交易员的访谈记录，让你浮光掠影了解一下顶级交易员。

***** 《大空头》 和 《贼巢》
两部关于华尔街内幕交易的纪实小说，非常精彩！《大空头》小说改编的电影，也是交易员必看的。
