#+title: 农村养老及保险购买
#+AUTHOR: panshishuo 
#+date: <2021-12-12 06:57>

***** 农村养老的需求

大概了解过农村的养老需求，不包括大病和丧事相关，一个老人（年龄超过 60），一年日常开销 15000，两个老人一年日常开销 20000，是属于比较基本的保障。就是说，一对夫妻，假如双方父母都是退休后 0 收入，那么一年养老开支得 40000。

这 2 万一年给老人，假如他们自己省着花，那基本还能有所结余。不得大病的话。按照 2020 年平均国人预期寿命 77 岁计算，从 60 到 77 岁一共 17 年，养老开支（包括一般的医疗和丧事相关），就需要准备 2 * 2 * 17 = 68 万。

绝大多数农村人其实是闲不住，假如老人有收入，那孩子相对轻松一些，可以给少一些。这里 1.5/2 万，是基于老人 0 收入的情况下。

不得不提的是一个最低保障的问题：农村养老最低的需求是 1 个老人一年 8000， 2 个老人一年 12000。不管这个钱是怎么得到的，老人基本的生活开销是需要这个数去保障的。

***** 购买保险的几个原则
1. 购买保险的重要性排序：居民医保 > 大病医保/惠民保 > 意外险 > 商业健康医疗保险/社保局养老保险 > 商业重疾险/定期寿险。

2. 购买保险被投保人顺序：最应该买的人，青壮年：意外险 + 重疾险 + 寿险，其次老人、小孩子。超过 50 岁：意外险。

3. 保额分配规则：
  - 寿险、意外险保额大概在年收入的 10 倍左右。
  - 重疾险保额 = 基础医疗费用支出 + 3 ~ 5 年工资收入。
  - 重疾险保额大概在 30 - 50 万；

4. 保费的投入：每年消费型保险保费尽量控制在年收入的 5% 以内，如果实在喜欢买分红型保险，保费不超过收入的 10%。

5. 保险的投保人与被保险人必须具有保险利益，即法律承认的经济利害关系：
  - 本人；
  - 配偶、子女、父母；
  - 前项以外与投保人有抚养、赡养、或者扶养关系的家庭其他成员、近亲属；
  - 与投保人有劳动关系（债务关系）的劳动者。除前款规定外，被保险人同意投保人为其订立合同的，视为投保人对被保险人具有保险利益。

***** 关于养老和医保
1. 全国非职工（农村）退休的话（除了北上外），也就是参加城乡居民基本养老保险，养老退休金国家给的基本就是 150 元人民币不到的基础上，然后加上自己累计交的部分（多交多得）；

2. 新型农村合作医疗（简称“新农合”）、城乡居民基本养老保险（简称“城乡居保”，曾经简称“新农保”），作为农村人是必须给自己或者父母交的，否则自己给自己或孩子挖坑。新农合的话，农村基本还能实际报销个 40% 左右的。虽然远不及职工医疗报销的比例，但是有比没有好的；

3. 新型农村合作医疗（简称“新农合”），和年龄无关，属于消费性保险，一年参保一次（一般是当年 9 月开始到 12 月月底投保次年的新农合），农村人超过 60 岁也要继续投保，才可以享受医保报销的；

4. 城乡居民基本养老保险（简称“城乡居保”，曾经简称“新农保”），集中缴费期各个省份不一样，档次也不一样（多交多领、也可以选择补交之前未交的），城乡居民基本养老保险（简称“城乡居保”，曾经简称“新农保”）缴费到 60 周岁前就可以了，60 岁以后，根据当地补贴和自己累计缴费的总和按照一定比例算出一个基本养老金。