#+title: 2021 年 12 月随笔
#+AUTHOR: panshishuo
#+date: <2021-11-30 17:24>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="static/myStyle.css" />
#+HTML_HEAD_EXTRA: <meta charset="utf-8">
#+HTML_HEAD_EXTRA: <script async type="text/javascript" src="https://cdn.rawgit.com/mathjax/MathJax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

**** 随想
- 什么是自由？自由是对公权力的批评不受公权力的制约，而不是自由的吃喝拉撒，那是猪。
- 如果你对每只向你吠的狗，都停下来扔石头，你永远到不了目的地。 —— 丘吉尔
- 一个国家走向怎样的未来，很大程度上取决于它如何面对自己的过去。正是从这个意义上来说，一个民族的悲剧其实也可以是它的财富，而拒绝挖掘这个财富则往往导致一个民族在历史的死胡同里原地踏步。
- 中国自秦以来，无所谓国也，皆家而已，一姓之兴则亿兆为之臣妾，其兴也，此一家之兴也，其亡也，此一家之亡也。天子一身，兼宪法，国家，王者三大物，其家亡则一切与之俱亡，顾其所利害者亦利害于一家而已，未尝为天下计也。 —— 严复
- 自由固不是钱所能买到的，但能够为钱而卖掉。
- 每当我听到有人说“我不知道怎么才能系统地学习这个东西”的时候，我在心里都把它翻译成“如果没人帮我整理好总结好并且手把手教我怎么做还得立刻看到效果的话，我就不打算花时间学它了”。当然，即便都整理好了，也不见得学。
- 一个人靠不靠谱，其实就看这三点：“凡事有交代，件件有着落，事事有回音。”
- 上学的目的，是为了追求人格的向上发展，并不是为了生活的安定。遗憾的是，我认为今天的教育，丧失了这最重要的目的。人们胡乱奢侈地花钱去接受大学教育，试图毕业后再设法去赚资本家的钱。但是，资本家不需要雇佣这么多的大学生，供需失衡，失业者增多势所必然。
- 抑郁症的发生，是”搞不定生活的困境“与”持续死磕的自己“的一场合谋。
- 我劝朋友，不管什么时候，都要开始尽可能地说真话，把该得罪的人都得罪光，这样剩下的都是真朋友了。我们要不逐利，寻真理，说真话。
- 精神濒临崩溃的症状之一，就是相信自己的工作非常重要。 —— 罗素
- 你需要做的就是开始，真的只是“开始”而已，其他的事情你会在做的过程中想明白。
- 制定一条难以执行的法律，不仅本身缺乏意义，还会损害其它法律的威严。如果来一条“买卖同罪”，势必须要再来一条“坦克进村”，以确保前者能得以执行。然而“坦克进村”是不可能的，所以“买卖同罪”也是不可能的。

**** 人类愚蠢定律
第一条基本定律：总是且不可避免地每个人都低估了流通中的愚蠢个体的数量。

第二条基本定律：某个人变得愚蠢的可能性与该人的任何其他特征无关。

第三条基本定律：（也是黄金定律）愚蠢的人是指在没有获得任何收益甚至可能蒙受损失的同时给另一人或一群人造成损失的人。

第四条基本定律：非愚蠢的人总是低估了愚蠢的个人的破坏力。特别是非愚蠢的人经常忘记，在任何时候，任何地方，在任何情况下与愚蠢的人打交道和/或与之交往总是一个代价高昂的错误。

第五条基本定律：愚蠢的人是最危险的人（该条的推理是：愚蠢的人比土匪更危险）。

**** 朋友少是正常
朋友少是正常的事情，根据“邓巴数字理论”，人类智力将允许人类拥有稳定社交网络的人数是 148 人，即：人类的社交人数上限为 150 人，精确交往深入跟踪交往的人数为 20 人左右。 人的大脑新皮层大小有限，提供的认知能力只能使一个人维持与大约 150 个人的稳定人际关系，这一数字是人们拥有的、与自己有私人关系的朋友数量。 也就是说，人们可能拥有 150 名好友，甚至更多社交网站的“好友”，但只维持与现实生活中大约 150 个人的“内部圈子”。而“内部圈子”好友在此理论中指一年至少联系一次的人。 再说的简单点，就是首富，他也最多只有 150 个朋友，多了也招呼不过来，而正常人，一般只能和 20 个人保持亲密关系。 这 20 个人里面，算上爸妈，兄弟姐妹，关系好的同事，领导，留给朋友的指标确实也只剩一两个。 所以，有一两个朋友，或者没有朋友，都很正常。

**** 什么是长期主义
长期主义，只有把时间拉长，我们才能在一个不确定的世界里，得到确定的答案。非长期主义者，只能得到“偶然”的成功，然后在一次次基本概率事件下，归于平庸。

长期，不是时间的线性，而是时间的“套娃”，所以，所谓的长期主义，是一种能穿越小周期，看透大周期的能力。

长期的挑战不是枯燥，而是各种不确定。我们没法在出发前作出完美的计划，但是我们必须做好万全的准备、甚至是超量的准备。不死掉，才能一直走下去。

**** 世界不是线性
很多人是线性思维，比如有 a 就会有 b，做了 a 那么 b 就应该发生。

线性思维的特点是理解不了事情的复杂性和系统性，比如学习是各种知识以及行动的组合，不是一个方法，而是一整套方法。

又比如婚姻和感情不是顺理成章，而是要像经营一家公司一样面对各种层面的问题，每一项没有处理好都会有问题。

所有非线性的，都会觉得难以理解，太麻烦。

问题是，生活本来就是大量复杂系统构成，各种因素各种力量各种因果。

想用一根线，去理解世界，太单纯。

**** 识字和阅读时两回事
识字和阅读是两回事。能阅读真正意义上的文章的人是少数。这就是为什么现在最流行的信息流形式是每几十个字就配一张图。即便这种每张图带几十个字的内容，受众比例仍然不大。

视频相对于文字来说，有效信息密度低得多，信息传递效率也低，并且难以检索。但视频的优点是可以覆盖几乎所有具有视力的人。这一个优点就可以弥补所有缺点。

而且视频传输信息的过程是连续的。你读书的时候可以一边读一边思考，但看视频的时候很少会这么做。这还不算完，视频的有效信息密度虽然低，但整体信息密度非常高。那些额外的信息就可以用来对受众进行潜移默化，进行暗示，进行操控。

所有这些，使得视频特别适合用来作为面向中下阶层的工具——无论是什么目的的工具。

**** 被很多人忽略却亟待恶补的能力
1. 复盘自己：观察自己的行为和情绪，能够用文字描述出来并加以分析。
2. 社交直觉：观察别人的行为和情绪，提高个人的社交直觉，更好的与别人相处、与自己相处。
3. 亲密关系：掌握维护一段关系的能力。

**** 别放纵自己的嫉恶如仇
电影《狩猎》中有这样一段话，大概意思：他们站在太阳下的高地来审视我，那些谴责我的人都站在道德上的高地，他们总是发出义正言辞的声音，以至于我们是很难去辩驳的。你无法辩驳，因为你是千夫所指。

“你看见是谁开的枪吗？我看不见，他在制高点他在阳光下。”

不要过分的放纵自己嫉恶如仇的那种私力救济的正义，我们要讲规则。不讲规则的正义，最终一定会导致非正义。人很容易陷入一种自欺，当你在做一件正义的事情时，你就觉得自己天生具有道德上的优越感，很容易会采取一些不恰当的手段。

**** 区域经济的真相
一批金融机构，看待区域经济真相是这样：
东北不碰、西北不去、蒙晋不沾；
河北保守、河南无为、天津负面；
赣桂太弱、湖南危险、海南太远；
京沪只有同业、西南只剩成渝、山东不出青济烟；
江浙处处好风景，除了徐连镇泰盐。

**** 物体的价值来源可以分为几类
1. 价值主要来自特定元素（同位素）。例如一根金条，一瓶重铀酸钠。
2. 价值主要来自元素的特定形态。例如一颗钻石，一片石墨烯。
3. 价值主要来自特定化合结构。例如一瓶胰岛素，一片阿司匹林。
4. 价值主要来自特定宏观结构。例如一个轴承，一根光纤。
5. 价值主要来自记录的信息。例如一页文件，一张照片

**** 人要讲理，得有良好的思考习惯。
人要讲理，得有良好的思考习惯。

比如想一想这个问题：一个人，加入传销组织被洗脑后，是不是失去自我死亡了一小部分？

然后需要反过来想一想：如果上述观点成立，那么一个自幼在传销组织长大的人，脱离传销组织后，是不是失去自我死亡了一小部分？

再跳出正反想一想：如果站在第三方视角，这两个观点就不可能只有一个是对的，要么全对，要么全错。

这时你会发现：而只有基于某个立场，才能得出一对一错的结论。

然后你需要确认：那么现在的讨论是基于某个立场，还是第三方视角？

更进一步还需要想想：立场是什么，第三方视角是否也是一个立场？

所以，悲哀的是，只有利己主义是最容易逻辑自洽的。搞别的主义都很费脑子，比较吃亏。搞之前得想好，搞得了搞不了。
