#+title: 2021 年 12 月随笔
#+AUTHOR: panshishuo
#+date: <2021-11-30 17:24>

***** 随想
- 什么是自由？自由是对公权力的批评不受公权力的制约，而不是自由的吃喝拉撒，那是猪。
- 如果你对每只向你吠的狗，都停下来扔石头，你永远到不了目的地。 —— 丘吉尔
- 一个国家走向怎样的未来，很大程度上取决于它如何面对自己的过去。正是从这个意义上来说，一个民族的悲剧其实也可以是它的财富，而拒绝挖掘这个财富则往往导致一个民族在历史的死胡同里原地踏步。
- 中国自秦以来，无所谓国也，皆家而已，一姓之兴则亿兆为之臣妾，其兴也，此一家之兴也，其亡也，此一家之亡也。天子一身，兼宪法，国家，王者三大物，其家亡则一切与之俱亡，顾其所利害者亦利害于一家而已，未尝为天下计也。 —— 严复
- 自由固不是钱所能买到的，但能够为钱而卖掉。
- 每当我听到有人说“我不知道怎么才能系统地学习这个东西”的时候，我在心里都把它翻译成“如果没人帮我整理好总结好并且手把手教我怎么做还得立刻看到效果的话，我就不打算花时间学它了”。当然，即便都整理好了，也不见得学。
- 一个人靠不靠谱，其实就看这三点：“凡事有交代，件件有着落，事事有回音。”
- 上学的目的，是为了追求人格的向上发展，并不是为了生活的安定。遗憾的是，我认为今天的教育，丧失了这最重要的目的。人们胡乱奢侈地花钱去接受大学教育，试图毕业后再设法去赚资本家的钱。但是，资本家不需要雇佣这么多的大学生，供需失衡，失业者增多势所必然。
- 抑郁症的发生，是”搞不定生活的困境“与”持续死磕的自己“的一场合谋。
- 我劝朋友，不管什么时候，都要开始尽可能地说真话，把该得罪的人都得罪光，这样剩下的都是真朋友了。我们要不逐利，寻真理，说真话。
- 精神濒临崩溃的症状之一，就是相信自己的工作非常重要。 —— 罗素
- 你需要做的就是开始，真的只是“开始”而已，其他的事情你会在做的过程中想明白。
- 制定一条难以执行的法律，不仅本身缺乏意义，还会损害其它法律的威严。如果来一条“买卖同罪”，势必须要再来一条“坦克进村”，以确保前者能得以执行。然而“坦克进村”是不可能的，所以“买卖同罪”也是不可能的。
- “人生总是这么痛苦吗？还是只有小时候这样？”“总是如此。”
- 年轻只有拼，人生没有捷径可走。
- 问错了问题，就不可能找到对的答案。应该在问什么问题上多下功夫。
- 在不损伤自己的前提下，帮助更多能够帮助到的人。做到这一点的人，这一生，活得都不会差。如果再精简一下，就是两个字：利他。
- 两个相爱的人，应该用你的爱去交换另一个人的爱。爱情才永远鲜活，谁都不可能要别人的全部。
- 学生离开学校时必须具备的就是沟通能力。日后的成功很大程度上取决于依次三种能力：说的能力、写的能力、想的品质。
- 互联网给我的感觉是：当你一两天没上网，可能就跟不上很多话题，错过很多节奏;但当你一个月没上网，就会发现好像啥也没错过，大为那些全都过气了。
- 我们需要警惕：消费习惯或欲望远高于其合法收入的人，都相当危险。
- 水果行将腐烂的时候，它会散发出一种异香。
- 年轻人对于社会的最大误解不是不切实际的幻想，而是在于认为人生存在一个简单的答案。
- 道德下降的第一个迹象，就是不关心事实辨别真相是累人的事。容易的办法，是把自己从这一负担解脱，让别人来告诉我谁是“坏人”，我只负责吃掉他。

***** 压力与动力
适当的压力会给人动力，但过大的压力对身心健康都是极其不利的。除了自身（偶尔还有医生），没人能真正判断我们所承受来自各方的压力有哪些、有多少、是否超过我们能够承受的范围。

远离那些看不得我们好的人。有些喜欢批评我们的人不一定是诤友，他们只是嘴贱而已。与之相处，我们一定会被严重消耗。

***** 吃苦的真正意义
大多数人对吃苦的含义可能理解的太肤浅。穷并不是吃苦。穷就是穷，吃苦不是忍受贫穷的能力。

吃苦的本质，是长时间为了某个目标而聚焦的能力，在这个过程中，放弃娱乐生活，放弃无效社交，放弃无意义的消费以及在过程中不被理解的孤独。它本质是一种自控力，自制力，坚持和深度思考的能力。

从很大程度上来说靠自己成功的富人，往往能比穷人更能吃苦耐劳，否则他不可能白手起家。你会看到他富有之后还是比普通人勤奋，比普通人能忍受孤独，还更有理想。这才是“吃苦”。

***** 人类愚蠢定律
第一条基本定律：总是且不可避免地每个人都低估了流通中的愚蠢个体的数量。

第二条基本定律：某个人变得愚蠢的可能性与该人的任何其他特征无关。

第三条基本定律：（也是黄金定律）愚蠢的人是指在没有获得任何收益甚至可能蒙受损失的同时给另一人或一群人造成损失的人。

第四条基本定律：非愚蠢的人总是低估了愚蠢的个人的破坏力。特别是非愚蠢的人经常忘记，在任何时候，任何地方，在任何情况下与愚蠢的人打交道和/或与之交往总是一个代价高昂的错误。

第五条基本定律：愚蠢的人是最危险的人（该条的推理是：愚蠢的人比土匪更危险）。

***** 朋友少是正常
朋友少是正常的事情，根据“邓巴数字理论”，人类智力将允许人类拥有稳定社交网络的人数是 148 人，即：人类的社交人数上限为 150 人，精确交往深入跟踪交往的人数为 20 人左右。 人的大脑新皮层大小有限，提供的认知能力只能使一个人维持与大约 150 个人的稳定人际关系，这一数字是人们拥有的、与自己有私人关系的朋友数量。 也就是说，人们可能拥有 150 名好友，甚至更多社交网站的“好友”，但只维持与现实生活中大约 150 个人的“内部圈子”。而“内部圈子”好友在此理论中指一年至少联系一次的人。 再说的简单点，就是首富，他也最多只有 150 个朋友，多了也招呼不过来，而正常人，一般只能和 20 个人保持亲密关系。 这 20 个人里面，算上爸妈，兄弟姐妹，关系好的同事，领导，留给朋友的指标确实也只剩一两个。 所以，有一两个朋友，或者没有朋友，都很正常。

真正的朋友，一定会越来越少，因为，走着走着，方向不一致了，性格不相容了，地位有悬殊了，所以才有“人生得一知己足矣”的感叹!不是总在一起吃喝玩乐的就是好朋友，患难舆共才是知己，这跟见面多少无关，跟有钱没钱无关，可一定跟是否善良，是否真诚，是否厚道有关!

不要在乎失去了谁，要去珍惜剩下的是谁。

***** 什么是长期主义
长期主义，只有把时间拉长，我们才能在一个不确定的世界里，得到确定的答案。非长期主义者，只能得到“偶然”的成功，然后在一次次基本概率事件下，归于平庸。

长期，不是时间的线性，而是时间的“套娃”，所以，所谓的长期主义，是一种能穿越小周期，看透大周期的能力。

长期的挑战不是枯燥，而是各种不确定。我们没法在出发前作出完美的计划，但是我们必须做好万全的准备、甚至是超量的准备。不死掉，才能一直走下去。

***** 世界不是线性
很多人是线性思维，比如有 a 就会有 b，做了 a 那么 b 就应该发生。

线性思维的特点是理解不了事情的复杂性和系统性，比如学习是各种知识以及行动的组合，不是一个方法，而是一整套方法。

又比如婚姻和感情不是顺理成章，而是要像经营一家公司一样面对各种层面的问题，每一项没有处理好都会有问题。

所有非线性的，都会觉得难以理解，太麻烦。

问题是，生活本来就是大量复杂系统构成，各种因素各种力量各种因果。

想用一根线，去理解世界，太单纯。

***** 识字和阅读时两回事
识字和阅读是两回事。能阅读真正意义上的文章的人是少数。这就是为什么现在最流行的信息流形式是每几十个字就配一张图。即便这种每张图带几十个字的内容，受众比例仍然不大。

视频相对于文字来说，有效信息密度低得多，信息传递效率也低，并且难以检索。但视频的优点是可以覆盖几乎所有具有视力的人。这一个优点就可以弥补所有缺点。

而且视频传输信息的过程是连续的。你读书的时候可以一边读一边思考，但看视频的时候很少会这么做。这还不算完，视频的有效信息密度虽然低，但整体信息密度非常高。那些额外的信息就可以用来对受众进行潜移默化，进行暗示，进行操控。

所有这些，使得视频特别适合用来作为面向中下阶层的工具——无论是什么目的的工具。

***** 被很多人忽略却亟待恶补的能力
1. 复盘自己：观察自己的行为和情绪，能够用文字描述出来并加以分析。
2. 社交直觉：观察别人的行为和情绪，提高个人的社交直觉，更好的与别人相处、与自己相处。
3. 亲密关系：掌握维护一段关系的能力。

***** 别放纵自己的嫉恶如仇
电影《狩猎》中有这样一段话，大概意思：他们站在太阳下的高地来审视我，那些谴责我的人都站在道德上的高地，他们总是发出义正言辞的声音，以至于我们是很难去辩驳的。你无法辩驳，因为你是千夫所指。

“你看见是谁开的枪吗？我看不见，他在制高点他在阳光下。”

不要过分的放纵自己嫉恶如仇的那种私力救济的正义，我们要讲规则。不讲规则的正义，最终一定会导致非正义。人很容易陷入一种自欺，当你在做一件正义的事情时，你就觉得自己天生具有道德上的优越感，很容易会采取一些不恰当的手段。

***** 区域经济的真相
一批金融机构，看待区域经济真相是这样：
东北不碰、西北不去、蒙晋不沾；
河北保守、河南无为、天津负面；
赣桂太弱、湖南危险、海南太远；
京沪只有同业、西南只剩成渝、山东不出青济烟；
江浙处处好风景，除了徐连镇泰盐。

***** 物体的价值来源可以分为几类
1. 价值主要来自特定元素（同位素）。例如一根金条，一瓶重铀酸钠。
2. 价值主要来自元素的特定形态。例如一颗钻石，一片石墨烯。
3. 价值主要来自特定化合结构。例如一瓶胰岛素，一片阿司匹林。
4. 价值主要来自特定宏观结构。例如一个轴承，一根光纤。
5. 价值主要来自记录的信息。例如一页文件，一张照片

***** 人要讲理，得有良好的思考习惯。
人要讲理，得有良好的思考习惯。

比如想一想这个问题：一个人，加入传销组织被洗脑后，是不是失去自我死亡了一小部分？

然后需要反过来想一想：如果上述观点成立，那么一个自幼在传销组织长大的人，脱离传销组织后，是不是失去自我死亡了一小部分？

再跳出正反想一想：如果站在第三方视角，这两个观点就不可能只有一个是对的，要么全对，要么全错。

这时你会发现：而只有基于某个立场，才能得出一对一错的结论。

然后你需要确认：那么现在的讨论是基于某个立场，还是第三方视角？

更进一步还需要想想：立场是什么，第三方视角是否也是一个立场？

所以，悲哀的是，只有利己主义是最容易逻辑自洽的。搞别的主义都很费脑子，比较吃亏。搞之前得想好，搞得了搞不了。

***** 人的精神三个阶段
人的精神有三个阶段：
1. 骆驼，由别人或命运被动安排的“我应当如何”阶段；
2. 狮子，怀疑“权威”，争取自我的“我要”阶段；
3. 婴儿，活在当下，享受现有一切的“我是”阶段。
尼采《查拉图斯特拉如是说》

***** 为什么要排斥独立思考的人？
有没有发现我们的社会特别排斥特立独行、我行我素、独立思考的人？

自由法治国家，法律是个体行为的唯一约束。但我们不是，我们看似拥有自由，但你实际上从小就被父母、老师、周围的舆论约束在一条读书、工作、结婚的既定轨道上。

任何发自内心、自由探索人生的尝试，不用其他人反对，我们自己都会先恐惧。

***** “傻逼”修炼手册
1. 光说有什么用？
2. 谁上来都一样！
3. 这世界没有绝对的公平！
4. 中国不能乱！
5. 美国也腐败！
6. 能当饭吃吗？
7. 这种事哪朝哪代都有！
8. 饿死人你看见了？
9. 轮得到你来指指点点？
10. 你算老几？关你啥事？
11. 中国太大了不好弄……
12. 总要有个过程……
13. 领导不比你笨！
14. 咱国家人太多了！

***** 柏杨在《丑陋的中国人里》提到
脏、乱、吵，窝里斗！三个中国人加在一起，就成了一头猪！

死不认错；为了掩饰一个错，不得不用很大的努力再制造更多的错，来证明第一个错并不是错。

喜欢装腔作势，记仇、缺乏包容性，中国人打一架可是三代都报不完的仇恨！

自傲、自卑，就是没有自尊，缺乏独立思考能力，更恐惧独立思考。没有是非、没有标准，只会抽风发飙。最后大家一起和稀泥。

***** 胡适谈治学要勤勉
“二战”爆发以后，胡适先生长期在美公干，这对师生又有了时相过从的机会。

胡适先生曾写信给吴健雄，殷殷嘱托："凡治学问，功力之外还需要天才。龟兔之喻，是勉励中人以下之语，也是警惕天才之语。有兔子的天才，加上乌龟的功力，定可以无敌于一世。仅有功力，可无大过，而未必有大成功。你是很聪明的人，千万自重自爱，将来成就未可限量。

这还不是我要对你说的话，我要对你说的是，希望你在海外住留期间，多注意此邦文物，多读文史类书，多读其他科学，使胸襟阔达，使见解高明，做一个博学的人。凡一流的科学家，都是极渊博的人，取精而用弘，由博而返约，故能有大成功。

***** 夏虫不可语冰
我现在不和人争吵了，因为我开始意识到，每个人只能在他的认知水准基础上去思考，以后有人告诉我 2 加 2 等于 10，我会说你真厉害你完全正确!

用一句话说就是：夏虫不可语冰，井蛙不可语海。

***** 到底什么是幸存者偏差
很少有人可以真正理解幸存者偏差，因为用来训练大脑的外在数据，大部分都是和幸存者和胜利者有关的。 如果说人类历史上各种斗争中的胜利者和失败者的比例是一比一百，那么你学习研究的各种原始资料和数据，也必须按照这种比例分配，才能建立更接近现实的思维模型。 但这几乎不可能。

这也意味着幸存者偏差永远是顽固的，每个拿破仑身材的人都幻想自己会有姚明穆铁柱的身高，每个投机者都拿索罗斯西蒙斯的特例来抬杠。

如何有什么工具可以做多幸存者偏差来谋利，一定要好好利用。

***** 如何成功且快乐 —— “尽人事，听天命”
大神比普通人不快乐得多，因为越卓越的人越不能忍受自己的平庸，有越高的自我期待，幸福感越低。

记得以前看过一篇文章，大意是成功人士和普通人相比都更焦虑，或者说容易焦虑本身才是向上的动力之一。反过来看，你要是很容易快乐，那也很难成功。

所以，“尽人事，听天命”。做不到前三个字，则难以成功。做不到后三个字，就难以快乐。

***** 习惯的力量
埃莫森说：“我们坚持做一件事，它会变得越来越容易。不是因为事情的性质变了，而是我们做事的能力增加了。”

当我们学会有意识地询问、无借口地倾听、勇于行动，我们就发展了自己以原则为中心而生活的能力，我们也就拥有了良好习惯的能力，习惯的力量是很强大的，当我们以一个机器人的要求要规范自己的行为，那么最终也会变成一个“机器人”：无比规律、无比自律、无比逻辑。当然，这并没有什么不好。只要想去做，就会得到改变。

—— 《要事第一》

***** 你以为的就是对的吗
一个没有见过自行车的观察者看到有人骑自行车过来，觉得两个轮子的自行车怎么能立得住，因而想把骑手叫停，并试图解决自行车立不稳的问题，而自行车一停下来自然会倒。

然而此时，观察者恐怕不会因为自己弄倒了一辆本来正常行驶的自行车而自省，反倒可能觉得自己担心的事情应验了。

***** 孩子的起跑线是父母自己

有一些父母，每天喝酒打牌，开口闭口违禁语，不懂尊重，不懂信任，从不学习不看书，只会刷抖音看直播，事业不求上进，生活不讲品行……，却总是要求自己的孩子要好好读书考上好大学找到好工作带父母飞黄腾达。

在这里求求你们了，别做梦了！你自己什么样子你心里没点数？放过孩子们吧。

事实上，孩子就是我们的一面镜子，他们的行为和意识，折射出我们生活中自己的一言一行，潜移默化中我们在自己孩子身上埋下的种子就生根发芽的，父母语言、行为的力量是不可小觑。

对我们而言，现在要做的，就是反思自己警醒过往，整理思路做好规划，从现在做起、从小事做起，自己想要自己的孩子是什么样子，自己首先应该去努力做成什么样子的。

孩子的起跑线其实是父母自己。

***** 我们缺的不是知识、是常识
我一直在说，中国缺的不是知识，中国缺得是常识。

用常识判断是非；用知识分析问题；用见识引导世人；用胆识主张发声。

然而在中国，只要心存良知，敢说真话，不屑谄媚的知识分子不是被消灭就是在逃亡。

这就是这个民族最可怕的一点，也是最终毁灭的前兆。
