#+title: 问题与主义论战
#+AUTHOR: panshishuo
#+date: <2021-12-20 15:09>

***** 多研究些问题，少谈些“主义”！
本报（《每周评论》）第二十八号里，我曾说过：

现在舆论界大危险，就是偏向纸上的学说，不去实地考察中国今日的社会需要究竟是什么东西。那些提倡尊孔祀天的人，固然是不懂得现时社会的需要。那些迷信军国民主义或无政府主义的人，就可算是懂得现时社会的需要么？

要知道舆论家的第一天职，就是细心考察社会的实在情形。一切学理，一切“主义”，都是这种考察的工具。有了学理做参考材料，便可使我们容易懂得所考察的情形，容易明白某种情形有什么意义，应该用什么救济的方法。

我这种议论，看许多人一定不愿意听。但是前几天北京《公言报》、《新民国报》、《新民报》（皆安福部的报），和日本文的《新支那报》，都极力恭维安福部首领王揖唐主张民生主义的演说，并且恭维安福部设立“民生主义的研究会”的办法。有许多人自然嘲笑这种假充时髦的行为。但是我看了这种消息，发生一种感想。这种感想是：“安福部也来高谈民生主义了，这不够给我们这班新舆论家一个教训吗？”什么教训呢？这可分三层说：

第一，空谈好听的“主义”，是极容易的事，是阿猫阿狗都能做的事，是鹦鹉和留声机器都能做的事。

第二，空谈外来进口的“主义”，是没有什么用处的。一切主义都是某时某地的有心人，对于那时那地的社会需要的救济方法。我们不去实地研究我们现在的社会需要，单会高谈某某主义，好比医生单记得许多汤头歌诀，不去研究病人的症候，如何能有用呢？

第三，偏向纸上的“主义”，是很危险的。这种口头禅很容易被无耻政客利用来做种种害人的事。欧洲政客和资本家利用国家主义的流毒，都是人所共知的。现在中国的政客，又要利用某种某种主义来欺人了。罗兰夫人说，“自由自由，天下多少罪恶，都是借你的名做出的！”一切好听的主义，都有这种危险。

这三条合起来看，可以看出“主义”的性质。凡“主义”都是应时势而起的。某种社会，到了某时代，受了某种的影响，呈现某种不满意的现状。于是有一些有心人，观察这种现象，想出某种救济的法子。这是“主义”的原起。主义初起时，大都是一种救时的具体主张。后来这种主张传播出去，传播的人要图简便，便用一两个字来代表这种具体的主张，所以叫他做“某某主义”。主张成了主义，便由具体的计划，变成一个抽象的名词。“主义”的弱点和危险就在这里。因为世间没有一个抽象名词能把某人某派的具体主张都包括在里面。比如“社会主义”一个名词，马克思的社会主义，和王揖唐的社会主义不同；你的社会主义，和我的社会主义不同：决不是这一个抽象名词所能包括。你谈你的社会主义，我谈我的社会主义，王揖唐又谈他的社会主义，同用一个名词，中间也许隔开七八个世纪，也许隔开两三万里路，然而你和我和王揖唐都可自称社会主义家，都可用这一个抽象名词来骗人。这不是“主义”的大缺点和大危险吗？

我再举现在人人嘴里挂着的“过激主义”做一个例：现在中国有几个人知道这一个名词做何意义？但是大家都痛恨痛骂“过激主义”，内务部下令严防“过激主义”，曹锟也行文严禁“过激主义”，卢永祥也出示查禁“过激主义”。前两个月，北京有几个老官僚在酒席上叹气，说，“不好了，过激派到了中国了。”前两天有一个小官僚，看见我写的一把扇子，大诧异道，“这不是过激党胡适吗？”哈哈，这就是“主义”的用处！

我因为深觉得高谈主义的危险，所以我现在奉劝新舆论界的同志道：“请你们多提出一些问题，少谈一些纸上的主义。”

更进一步说：“请你们多多研究这个问题如何解决，那个问题如何解决，不要高谈这种主义如何新奇，那种主义如何奥妙。”

现在中国应该赶紧解决的问题，真多得很。从人力车夫的生计问题，到大总统的权限问题；从卖淫问题到卖官卖国问题；从解散安福部问题到加入国际联盟问题；从女子解放问题到男子解放问题……那一个不是火烧眉毛紧急问题？

我们不去研究人力车夫的生计，却去高谈社会主义；不去研究女子如何解放，家庭制度如何救正，却去高谈公妻主义和自由恋爱；不去研究安福部如何解散，不去研究南北问题如何解决，却去高谈无政府主义；我们还要得意扬扬夸口道，我们所谈的是根本“解决”。老实说罢，这是自欺欺人的梦话，这是中国思想界破产的铁证，这是中国社会改良的死刑宣告！

为什么谈主义的人那么多，为什么研究问题的人那么少呢？这都由于一个懒字。懒的定义是避难就易。研究问题是极困难的事，高谈主义是极容易的事。比如研究安福部如何解散，研究南北和议如何解决，这都是要费工夫，挖心血，收集材料，征求意见，考察情形，还要冒险吃苦，方才可以得一种解决的意见。又没有成例可援，又没有黄梨洲、柏拉图的话可引，又没有《大英百科全书》可查，全凭研究考察的工夫：这岂不是难事吗？高谈“无政府主义”便不同了。买一两本实社《自由录》，看一两本西文无政府主义的小册子，再翻一翻《大英百科全书》，便可以高谈无忌了：这岂不是极容易的事吗？

高谈主义，不研究问题的人，只是畏难求易，只是懒。

凡是有价值的思想，都是从这个那个具体的问题下手的。先研究了问题的种种方面的种种的事实，看看究竟病在何处，这是思想的第一步工夫。然后根据于一生经验学问，提出种种解决的方法，提出种种医病的丹方，这是思想的第二步工夫。然后用一生的经验学问，加上想像的能力，推想每一种假定的解决法，该有什么样的效果，推想这种效果是否真能解决眼前这个困难问题。推想的结果，拣定一种假定的解决，认为我的主张，这是思想的第三步工夫。凡是有价值的主张，都是先经过这三步工夫来的。不如此，不算舆论家，只可算是抄书手。

读者不要误会我的意思。我并不是劝人不研究一切学说和一切“主义”。学理是我们研究问题的一种工具。没有学理做工具，就如同王阳明对着竹子痴坐，妄想“格物”，那是做不到的事。种种学说和主义，我们都应该研究。有了许多学理做材料，见了具体的问题，方才能寻出一个解决的方法。但是我希望中国的舆论家，把一切“主义”摆在脑背后，做参考资料，不要挂在嘴上做招牌，不要叫一知半解的人拾了这些半生不熟的主义去做口头禅。

“主义”的大危险，就是能使人心满意足，自以为寻着包医百病的“根本解决”，从此用不着费心力去研究这个那个具体问题的解决法了。

民国八年七月

（原载 1919 年 7 月 20 日《每周评论》第 31 号）
