#+title: 殷海光总结的七种谬误
#+AUTHOR: panshishuo
#+date: <2021-12-29 12:30>

#+BEGIN_QUOTE
在 [[https://item.jd.com/12403813.html][《逻辑新引：怎样判别是非》（殷海光 著）]] 中，殷海光首先用一章的内容，告诉我们谬误有哪些。或者说，造成谬误的原因以及方式，有哪几种？殷海光归类为一下七种：
#+END_QUOTE

***** 诉诸群众
第一种，叫“诉诸群众”。

也就是我们常常听到的“多数乃真理的标准”，这种情况在历史上太多了，好比伽利略支持哥白尼的日心说，当时教廷的人就说，我们所有人以及我们以前的所有人都相信太阳绕地球转，所以伽利略的学说肯定是错的。当时一万个农民的科学知识也比不上一个伽利略。如果这个成立的话，那中国人说什么都是真理，我们人口最多啊，对不对？

***** 诉诸权威
第二种，叫“诉诸权威”。

在一个没有被启蒙的社会，权威特别奏效。权威当然不能没有，但是如果整个社会只有一个权威，那可就糟糕了。知识爆炸以来，又不是亚里士多德、达·芬奇的年代，达·芬奇可以是各种家 -- 画家、作家、数学家、科学家、医学家……，你今天行吗？今天已经是“多元权威”的年代，所以千万别相信外行的“权威”说的话，听说一个人是权威，要问问是什么权威。

***** 诉诸暴力
第三种，叫“诉诸暴力”。

中国人有句古话叫“秀才遇到兵，有理说不清”，这招太厉害了！如果没道理，我们可以用暴力建构出一个道理。古代的土匪流寇，最喜欢打一个旗号叫“替天行道”，有了这个护身符，杀人就可以理直气壮了。借助暴力巩固真理在一定的时空内是管用的，二战的时候丘吉尔向斯大林提议一起去说服教皇参战，斯大林很鄙视地问：“教皇有多少军队？”

***** 诉诸怜悯
第四种，叫“诉诸怜悯”。

就是说，哎呀，我虽然没有什么道理吧，但是我的心是好的呀。

***** 人身攻击
第五种，叫“人身攻击”。

就是我在道理上说不过你，我还是有办法打倒你，就是给你泼脏水，说你私生活不检点等。受过逻辑训练的人会知道，一个人的言论和他的道德没有关系。反过来也一样的，不是说一个人在道德上多高尚，他说的话就对。其实古人也有这种智慧，叫“不以人废言，不以言举人”。

***** 以自我为中心
第六种，叫“以自我为中心”。

不要和我辩论，反正我的就是对的，别人的就是错的。这个“我”可以扩大，比如只要是“我的民族”的就是对的，“我的国家”的就是对的。法西斯主义盛行时的德国和军国主义盛行时的日本，就是这样。

***** 过分简单
第七种，叫“过分简单”。

世界是很复杂的，但人是很不耐烦的，你要是跟他讲复杂的道理，他不要听。所以，人天生倾向取信简单的道理。

***** 小结
以上就是 殷海光 总结的七种谬误的种类，算是很全面了。你看，我们是不是很容易就犯错呢？

其实心智成熟的人都知道，真理是不易得的，很辛苦的。获得真理很困难，但失去真理却很容易。而且除了辛苦以外，还要用正确的方法才能获得真理。

