#+title: 2021 年 11 月随笔
#+AUTHOR: panshishuo
#+date: <2021-11-30 15:57>

***** 随想
- 真正能缓解焦虑的，却是总想偷懒不做的事情。
- 一个人知道自己为什么而活，就可以忍受任何一种生活。
- 少女 > 儿童 > 少妇 > 老人 > 狗 > 男人，据说是投资消费领域的人总结出来的市场价值。
- 将个人处境归咎于原生家庭，往往是逃避的借口。
- 那些发财的路，并不是写在刑法里面，而是要跟着美联储和人行作对。它们发钱，你要买资产；它们收钱，你要守着钱。
- 每个成年人要为自己的行为负责，要有所为有所不为，不能随心所欲的想做什么就做什么。
- 朋友圈就算热情似火，人们最终还是会选择表现出冷漠。

***** 克服懦弱远比职业规划重要
一个人的人性，才是他人生的天花板。
绝大部分人的问题根本不是什么职业规划问题 —— 而是他们人性的丑恶和懦弱。至于说什么职业规划 —— 请问，给你规划了，你敢去做吗？

最好的职业规划，从来都是尊重本心，想做就去做，直面自己的欲望，直面所有面临的风险。能承受失败，才配得上成功。但是大部分人渴望的职业规划是 —— 零风险走向成功。
请问 —— 他们配吗？

凭什么他们家庭条件又差、学历又不好、人又怂，然后这个世界专门为他们准备一条路，可以零风险成功呢？对不起。没有这条路。如果有这条路，那就是骗你的。

解决方法是什么？先承担风险，才有可能有未来。
记住，承担风险，不一定有未来。但是不承担风险，永远没有未来。承担风险，可能是找死，但是不承担风险，是等死。如果是我，我宁愿找死也不等死。只不过大部分人 —— 宁愿等死，也不找死。

看过丧尸片么？当丧尸来的时候。所有想躲在房子里不跑等着别人来救的人，最后都死了。只有勇敢的跑出去的人，才有一线生机。你现在就是在房子里等死的人。

遭遇危机的社畜，这方便暴露的人性 —— 就是懦弱。不克服懦弱，一切规划都是扯淡。规划的第一要素并不是规划本身完不完美 —— 而是执行力。但是懦弱的人都没有执行力。因为执行需要风险，意淫没有风险。

***** 成事的四步
1. 知道哪些可以做。
2. 判断什么最值得做。
3. 有魄力果断投入去做。
4. 有能力把事做成。
四点缺一不可。缺了任何一点都无法成事。所以成事很难。
第 2、3 两点看起来最没技术含量，却也是最多人欠缺的。

***** 谈谈搞钱的方式
谈谈搞到钱的方式，一般而言就 3 个 —— 卖东西变现、讨债、借钱。

1. 卖东西变现：我们经常会买到一些不怎用的东西，比如衣服、写字、书、健身器……，这些东西放在家里越久越贬值，还不如卖了换些钱的；其次是卖一些资产，房子、车子、股票、债券、收藏品等；

2. 讨债：亲戚朋友问你借的钱，这个时候，你恰巧又缺钱，就可以理直气壮的去讨债的，当然讨债还是讲究技巧的，这部分钱是最值得被要回来；

3. 借钱：可以问家人、亲戚、朋友借钱，当然最好是可以在借钱的时候，就约定还款的方式和时间；也可以信用贷、抵押贷；当然还可以直接刷卡信用卡借钱（要注意的是，信用卡套现的利息很高、而且计息是从借出来时候就算）。

三种方式的依次优先顺序是：卖东西变现 > 讨债 > 借钱（亲朋借钱 > 信用贷、抵押贷 > 信用卡套现），坚决抵制高利贷、网贷的借钱方式，这是饮鸩止渴。

最后，要说的是，要有一定的理财规划意识，避免自己进去财务危机，需要借钱的时候，往往可以算作是一种财务危机，理财规划的一个最简单的措施是：预留 3 - 6 个月日常生活月支出，最好的话是 12 个月（具体以家庭和个人的情况自定）。

最开始攒备用金时是很痛苦的，因为往往属于没钱可攒，这个时候一方面要开源、更重要的是要节流减少不必要的开支，节流中强制储蓄的一个有效的措施：在拿到收入的那一刻，就强制的储蓄一定的比例，一般为收入的 10% 以上，假如实在困难，也请坚持强制储蓄 5% 的。切忌：先花着，等月底有钱了再存。
